
############### ENGLISH ###############

INSERT INTO currency(id,country,currency,code,lang) VALUES (1,'Afghanistan','Afghan afghani','AFN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2,'Akrotiri and Dhekelia (UK)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (3,'Aland Islands (Finland)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (4,'Albania','Albanian lek','ALL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (5,'Algeria','Algerian dinar','DZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (6,'American Samoa (USA)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (7,'Andorra','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (8,'Angola','Angolan kwanza','AOA','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (9,'Anguilla (UK)','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (10,'Antigua and Barbuda','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (11,'Argentina','Argentine peso','ARS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (12,'Armenia','Armenian dram','AMD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (13,'Aruba (Netherlands)','Aruban florin','AWG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (14,'Ascension Island (UK)','Saint Helena pound','SHP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (15,'Australia','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (16,'Austria','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (17,'Azerbaijan','Azerbaijan manat','AZN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (18,'Bahamas','Bahamian dollar','BSD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (19,'Bahrain','Bahraini dinar','BHD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (20,'Bangladesh','Bangladeshi taka','BDT','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (21,'Barbados','Barbadian dollar','BBD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (22,'Belarus','Belarusian ruble','BYN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (23,'Belgium','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (24,'Belize','Belize dollar','BZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (25,'Benin','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (26,'Bermuda (UK)','Bermudian dollar','BMD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (27,'Bhutan','Bhutanese ngultrum','BTN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (28,'Bolivia','Bolivian boliviano','BOB','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (29,'Bonaire (Netherlands)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (30,'Bosnia and Herzegovina','Bosnia and Herzegovina convertible mark','BAM','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (31,'Botswana','Botswana pula','BWP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (32,'Brazil','Brazilian real','BRL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (33,'British Indian Ocean Territory (UK)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (34,'British Virgin Islands (UK)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (35,'Brunei','Brunei dollar','BND','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (36,'Bulgaria','Bulgarian lev','BGN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (37,'Burkina Faso','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (38,'Burundi','Burundi franc','BIF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (39,'Cabo Verde','Cape Verdean escudo','CVE','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (40,'Cambodia','Cambodian riel','KHR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (41,'Cameroon','Central African CFA franc','XAF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (42,'Canada','Canadian dollar','CAD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (43,'Caribbean Netherlands (Netherlands)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (44,'Cayman Islands (UK)','Cayman Islands dollar','KYD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (45,'Central African Republic','Central African CFA franc','XAF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (46,'Chad','Central African CFA franc','XAF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (47,'Chatham Islands (New Zealand)','New Zealand dollar','NZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (48,'Chile','Chilean peso','CLP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (49,'China','Chinese Yuan Renminbi','CNY','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (50,'Christmas Island (Australia)','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (51,'Cocos (Keeling) Islands (Australia)','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (52,'Colombia','Colombian peso','COP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (53,'Comoros','Comorian franc','KMF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (54,'Congo, Democratic Republic of the','Congolese franc','CDF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (55,'Congo, Republic of the','Central African CFA franc','XAF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (56,'Cook Islands (New Zealand)','Cook Islands dollar','---','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (57,'Costa Rica','Costa Rican colon','CRC','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (58,'Cote d''Ivoire','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (59,'Croatia','Croatian kuna','HRK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (60,'Cuba','Cuban peso','CUP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (61,'Curacao (Netherlands)','Netherlands Antillean guilder','ANG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (62,'Cyprus','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (63,'Czechia','Czech koruna','CZK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (64,'Denmark','Danish krone','DKK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (65,'Djibouti','Djiboutian franc','DJF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (66,'Dominica','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (67,'Dominican Republic','Dominican peso','DOP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (68,'Ecuador','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (69,'Egypt','Egyptian pound','EGP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (70,'El Salvador','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (71,'Equatorial Guinea','Central African CFA franc','XAF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (72,'Eritrea','Eritrean nakfa','ERN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (73,'Estonia','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (74,'Eswatini (formerly Swaziland)','Swazi lilangeni','SZL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (75,'Ethiopia','Ethiopian birr','ETB','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (76,'Falkland Islands (UK)','Falkland Islands pound','FKP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (77,'Faroe Islands (Denmark)','Faroese krona','---','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (78,'Fiji','Fijian dollar','FJD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (79,'Finland','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (80,'France','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (81,'French Guiana (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (82,'French Polynesia (France)','CFP franc','XPF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (83,'Gabon','Central African CFA franc','XAF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (84,'Gambia','Gambian dalasi','GMD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (85,'Georgia','Georgian lari','GEL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (86,'Germany','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (87,'Ghana','Ghanaian cedi','GHS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (88,'Gibraltar (UK)','Gibraltar pound','GIP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (89,'Greece','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (90,'Greenland (Denmark)','Danish krone','DKK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (91,'Grenada','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (92,'Guadeloupe (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (93,'Guam (USA)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (94,'Guatemala','Guatemalan quetzal','GTQ','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (95,'Guernsey (UK)','Guernsey Pound','GGP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (96,'Guinea','Guinean franc','GNF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (97,'Guinea-Bissau','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (98,'Guyana','Guyanese dollar','GYD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (99,'Haiti','Haitian gourde','HTG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (100,'Honduras','Honduran lempira','HNL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (101,'Hong Kong (China)','Hong Kong dollar','HKD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (102,'Hungary','Hungarian forint','HUF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (103,'Iceland','Icelandic krona','ISK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (104,'India','Indian rupee','INR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (105,'Indonesia','Indonesian rupiah','IDR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (106,'International Monetary Fund (IMF)','SDR (Special Drawing Right)','XDR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (107,'Iran','Iranian rial','IRR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (108,'Iraq','Iraqi dinar','IQD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (109,'Ireland','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (110,'Isle of Man (UK)','Manx pound','IMP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (111,'Israel','Israeli new shekel','ILS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (112,'Italy','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (113,'Jamaica','Jamaican dollar','JMD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (114,'Japan','Japanese yen','JPY','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (115,'Jersey (UK)','Jersey pound','JEP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (116,'Jordan','Jordanian dinar','JOD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (117,'Kazakhstan','Kazakhstani tenge','KZT','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (118,'Kenya','Kenyan shilling','KES','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (119,'Kiribati','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (120,'Kosovo','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (121,'Kuwait','Kuwaiti dinar','KWD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (122,'Kyrgyzstan','Kyrgyzstani som','KGS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (123,'Laos','Lao kip','LAK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (124,'Latvia','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (125,'Lebanon','Lebanese pound','LBP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (126,'Lesotho','Lesotho loti','LSL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (127,'Liberia','Liberian dollar','LRD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (128,'Libya','Libyan dinar','LYD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (129,'Liechtenstein','Swiss franc','CHF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (130,'Lithuania','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (131,'Luxembourg','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (132,'Macau (China)','Macanese pataca','MOP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (133,'Madagascar','Malagasy ariary','MGA','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (134,'Malawi','Malawian kwacha','MWK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (135,'Malaysia','Malaysian ringgit','MYR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (136,'Maldives','Maldivian rufiyaa','MVR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (137,'Mali','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (138,'Malta','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (139,'Marshall Islands','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (140,'Martinique (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (141,'Mauritania','Mauritanian ouguiya','MRU','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (142,'Mauritius','Mauritian rupee','MUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (143,'Mayotte (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (144,'Mexico','Mexican peso','MXN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (145,'Micronesia','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (146,'Moldova','Moldovan leu','MDL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (147,'Monaco','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (148,'Mongolia','Mongolian tugrik','MNT','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (149,'Montenegro','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (150,'Montserrat (UK)','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (151,'Morocco','Moroccan dirham','MAD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (152,'Mozambique','Mozambican metical','MZN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (153,'Myanmar (formerly Burma)','Myanmar kyat','MMK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (154,'Namibia','Namibian dollar','NAD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (155,'Nauru','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (156,'Nepal','Nepalese rupee','NPR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (157,'Netherlands','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (158,'New Caledonia (France)','CFP franc','XPF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (159,'New Zealand','New Zealand dollar','NZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (160,'Nicaragua','Nicaraguan cordoba','NIO','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (161,'Niger','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (162,'Nigeria','Nigerian naira','NGN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (163,'Niue (New Zealand)','New Zealand dollar','NZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (164,'Norfolk Island (Australia)','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (165,'Northern Mariana Islands (USA)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (166,'North Korea','North Korean won','KPW','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (167,'North Macedonia (formerly Macedonia)','Macedonian denar','MKD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (168,'Norway','Norwegian krone','NOK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (169,'Oman','Omani rial','OMR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (170,'Pakistan','Pakistani rupee','PKR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (171,'Palau','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (172,'Palestine','Israeli new shekel','ILS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (173,'Panama','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (174,'Papua New Guinea','Papua New Guinean kina','PGK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (175,'Paraguay','Paraguayan guarani','PYG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (176,'Peru','Peruvian sol','PEN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (177,'Philippines','Philippine peso','PHP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (178,'Pitcairn Islands (UK)','New Zealand dollar','NZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (179,'Poland','Polish zloty','PLN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (180,'Portugal','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (181,'Puerto Rico (USA)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (182,'Qatar','Qatari riyal','QAR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (183,'Reunion (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (184,'Romania','Romanian leu','RON','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (185,'Russia','Russian ruble','RUB','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (186,'Rwanda','Rwandan franc','RWF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (187,'Saba (Netherlands)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (188,'Saint Barthelemy (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (189,'Saint Helena (UK)','Saint Helena pound','SHP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (190,'Saint Kitts and Nevis','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (191,'Saint Lucia','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (192,'Saint Martin (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (193,'Saint Pierre and Miquelon (France)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (194,'Saint Vincent and the Grenadines','East Caribbean dollar','XCD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (195,'Samoa','Samoan tala','WST','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (196,'San Marino','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (197,'Sao Tome and Principe','Sao Tome and Principe dobra','STN','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (198,'Saudi Arabia','Saudi Arabian riyal','SAR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (199,'Senegal','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (200,'Serbia','Serbian dinar','RSD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (201,'Seychelles','Seychellois rupee','SCR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (202,'Sierra Leone','Sierra Leonean leone','SLL','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (203,'Singapore','Singapore dollar','SGD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (204,'Sint Eustatius (Netherlands)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (205,'Sint Maarten (Netherlands)','Netherlands Antillean guilder','ANG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (206,'Slovakia','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (207,'Slovenia','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (208,'Solomon Islands','Solomon Islands dollar','SBD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (209,'Somalia','Somali shilling','SOS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (210,'South Africa','South African rand','ZAR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (211,'South Georgia Island (UK)','Pound sterling','GBP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (212,'South Korea','South Korean won','KRW','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (213,'South Sudan','South Sudanese pound','SSP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (214,'Spain','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (215,'Sri Lanka','Sri Lankan rupee','LKR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (216,'Sudan','Sudanese pound','SDG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (217,'Suriname','Surinamese dollar','SRD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (218,'Svalbard and Jan Mayen (Norway)','Norwegian krone','NOK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (219,'Sweden','Swedish krona','SEK','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (220,'Switzerland','Swiss franc','CHF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (221,'Syria','Syrian pound','SYP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (222,'Taiwan','New Taiwan dollar','TWD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (223,'Tajikistan','Tajikistani somoni','TJS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (224,'Tanzania','Tanzanian shilling','TZS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (225,'Thailand','Thai baht','THB','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (226,'Timor-Leste','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (227,'Togo','West African CFA franc','XOF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (228,'Tokelau (New Zealand)','New Zealand dollar','NZD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (229,'Tonga','Tongan pa’anga','TOP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (230,'Trinidad and Tobago','Trinidad and Tobago dollar','TTD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (231,'Tristan da Cunha (UK)','Pound sterling','GBP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (232,'Tunisia','Tunisian dinar','TND','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (233,'Turkey','Turkish lira','TRY','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (234,'Turkmenistan','Turkmen manat','TMT','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (235,'Turks and Caicos Islands (UK)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (236,'Tuvalu','Australian dollar','AUD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (237,'Uganda','Ugandan shilling','UGX','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (238,'Ukraine','Ukrainian hryvnia','UAH','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (239,'United Arab Emirates','UAE dirham','AED','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (240,'United Kingdom','Pound sterling','GBP','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (241,'United States of America','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (242,'Uruguay','Uruguayan peso','UYU','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (243,'US Virgin Islands (USA)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (244,'Uzbekistan','Uzbekistani som','UZS','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (245,'Vanuatu','Vanuatu vatu','VUV','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (246,'Vatican City (Holy See)','European euro','EUR','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (247,'Venezuela','Venezuelan bolivar','VES','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (248,'Vietnam','Vietnamese dong','VND','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (249,'Wake Island (USA)','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (250,'Wallis and Futuna (France)','CFP franc','XPF','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (251,'Yemen','Yemeni rial','YER','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (252,'Zambia','Zambian kwacha','ZMW','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (253,'Zimbabwe','United States dollar','USD','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (254,'','Gold','XAU','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (255,'','Silver','XAG','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (256,'','Platinum','XPT','en');
INSERT INTO currency(id,country,currency,code,lang) VALUES (257,'','Palladium','XPD','en');

############### RUSSIAN ###############
# TASK: Translate to Russian

INSERT INTO currency(id,country,currency,code,lang) VALUES (1001,'Afghanistan','Afghan afghani','AFN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1002,'Akrotiri and Dhekelia (UK)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1003,'Aland Islands (Finland)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1004,'Albania','Albanian lek','ALL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1005,'Algeria','Algerian dinar','DZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1006,'American Samoa (USA)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1007,'Andorra','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1008,'Angola','Angolan kwanza','AOA','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1009,'Anguilla (UK)','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1010,'Antigua and Barbuda','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1011,'Argentina','Argentine peso','ARS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1012,'Armenia','Armenian dram','AMD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1013,'Aruba (Netherlands)','Aruban florin','AWG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1014,'Ascension Island (UK)','Saint Helena pound','SHP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1015,'Australia','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1016,'Austria','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1017,'Azerbaijan','Azerbaijan manat','AZN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1018,'Bahamas','Bahamian dollar','BSD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1019,'Bahrain','Bahraini dinar','BHD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1020,'Bangladesh','Bangladeshi taka','BDT','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1021,'Barbados','Barbadian dollar','BBD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1022,'Belarus','Belarusian ruble','BYN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1023,'Belgium','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1024,'Belize','Belize dollar','BZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1025,'Benin','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1026,'Bermuda (UK)','Bermudian dollar','BMD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1027,'Bhutan','Bhutanese ngultrum','BTN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1028,'Bolivia','Bolivian boliviano','BOB','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1029,'Bonaire (Netherlands)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1030,'Bosnia and Herzegovina','Bosnia and Herzegovina convertible mark','BAM','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1031,'Botswana','Botswana pula','BWP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1032,'Brazil','Brazilian real','BRL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1033,'British Indian Ocean Territory (UK)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1034,'British Virgin Islands (UK)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1035,'Brunei','Brunei dollar','BND','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1036,'Bulgaria','Bulgarian lev','BGN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1037,'Burkina Faso','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1038,'Burundi','Burundi franc','BIF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1039,'Cabo Verde','Cape Verdean escudo','CVE','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1040,'Cambodia','Cambodian riel','KHR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1041,'Cameroon','Central African CFA franc','XAF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1042,'Canada','Canadian dollar','CAD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1043,'Caribbean Netherlands (Netherlands)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1044,'Cayman Islands (UK)','Cayman Islands dollar','KYD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1045,'Central African Republic','Central African CFA franc','XAF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1046,'Chad','Central African CFA franc','XAF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1047,'Chatham Islands (New Zealand)','New Zealand dollar','NZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1048,'Chile','Chilean peso','CLP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1049,'China','Chinese Yuan Renminbi','CNY','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1050,'Christmas Island (Australia)','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1051,'Cocos (10Keeling) Islands (Australia)','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1052,'Colombia','Colombian peso','COP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1053,'Comoros','Comorian franc','KMF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1054,'Congo, Democratic Republic of the','Congolese franc','CDF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1055,'Congo, Republic of the','Central African CFA franc','XAF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1056,'Cook Islands (New Zealand)','Cook Islands dollar','---','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1057,'Costa Rica','Costa Rican colon','CRC','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1058,'Cote d''Ivoire','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1059,'Croatia','Croatian kuna','HRK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1060,'Cuba','Cuban peso','CUP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1061,'Curacao (Netherlands)','Netherlands Antillean guilder','ANG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1062,'Cyprus','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1063,'Czechia','Czech koruna','CZK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1064,'Denmark','Danish krone','DKK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1065,'Djibouti','Djiboutian franc','DJF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1066,'Dominica','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1067,'Dominican Republic','Dominican peso','DOP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1068,'Ecuador','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1069,'Egypt','Egyptian pound','EGP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1070,'El Salvador','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1071,'Equatorial Guinea','Central African CFA franc','XAF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1072,'Eritrea','Eritrean nakfa','ERN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1073,'Estonia','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1074,'Eswatini (formerly Swaziland)','Swazi lilangeni','SZL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1075,'Ethiopia','Ethiopian birr','ETB','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1076,'Falkland Islands (UK)','Falkland Islands pound','FKP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1077,'Faroe Islands (Denmark)','Faroese krona','---','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1078,'Fiji','Fijian dollar','FJD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1079,'Finland','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1080,'France','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1081,'French Guiana (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1082,'French Polynesia (France)','CFP franc','XPF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1083,'Gabon','Central African CFA franc','XAF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1084,'Gambia','Gambian dalasi','GMD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1085,'Georgia','Georgian lari','GEL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1086,'Germany','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1087,'Ghana','Ghanaian cedi','GHS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1088,'Gibraltar (UK)','Gibraltar pound','GIP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1089,'Greece','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1090,'Greenland (Denmark)','Danish krone','DKK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1091,'Grenada','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1092,'Guadeloupe (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1093,'Guam (USA)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1094,'Guatemala','Guatemalan quetzal','GTQ','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1095,'Guernsey (UK)','Guernsey Pound','GGP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1096,'Guinea','Guinean franc','GNF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1097,'Guinea-Bissau','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1098,'Guyana','Guyanese dollar','GYD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1099,'Haiti','Haitian gourde','HTG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1100,'Honduras','Honduran lempira','HNL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1101,'Hong Kong (China)','Hong Kong dollar','HKD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1102,'Hungary','Hungarian forint','HUF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1103,'Iceland','Icelandic krona','ISK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1104,'India','Indian rupee','INR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1105,'Indonesia','Indonesian rupiah','IDR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1106,'International Monetary Fund (1IMF)','SDR (1Special Drawing Right)','XDR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1107,'Iran','Iranian rial','IRR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1108,'Iraq','Iraqi dinar','IQD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1109,'Ireland','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1110,'Isle of Man (UK)','Manx pound','IMP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1111,'Israel','Israeli new shekel','ILS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1112,'Italy','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1113,'Jamaica','Jamaican dollar','JMD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1114,'Japan','Japanese yen','JPY','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1115,'Jersey (UK)','Jersey pound','JEP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1116,'Jordan','Jordanian dinar','JOD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1117,'Kazakhstan','Kazakhstani tenge','KZT','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1118,'Kenya','Kenyan shilling','KES','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1119,'Kiribati','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1120,'Kosovo','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1121,'Kuwait','Kuwaiti dinar','KWD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1122,'Kyrgyzstan','Kyrgyzstani som','KGS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1123,'Laos','Lao kip','LAK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1124,'Latvia','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1125,'Lebanon','Lebanese pound','LBP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1126,'Lesotho','Lesotho loti','LSL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1127,'Liberia','Liberian dollar','LRD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1128,'Libya','Libyan dinar','LYD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1129,'Liechtenstein','Swiss franc','CHF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1130,'Lithuania','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1131,'Luxembourg','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1132,'Macau (China)','Macanese pataca','MOP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1133,'Madagascar','Malagasy ariary','MGA','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1134,'Malawi','Malawian kwacha','MWK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1135,'Malaysia','Malaysian ringgit','MYR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1136,'Maldives','Maldivian rufiyaa','MVR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1137,'Mali','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1138,'Malta','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1139,'Marshall Islands','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1140,'Martinique (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1141,'Mauritania','Mauritanian ouguiya','MRU','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1142,'Mauritius','Mauritian rupee','MUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1143,'Mayotte (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1144,'Mexico','Mexican peso','MXN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1145,'Micronesia','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1146,'Moldova','Moldovan leu','MDL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1147,'Monaco','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1148,'Mongolia','Mongolian tugrik','MNT','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1149,'Montenegro','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1150,'Montserrat (UK)','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1151,'Morocco','Moroccan dirham','MAD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1152,'Mozambique','Mozambican metical','MZN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1153,'Myanmar (formerly Burma)','Myanmar kyat','MMK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1154,'Namibia','Namibian dollar','NAD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1155,'Nauru','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1156,'Nepal','Nepalese rupee','NPR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1157,'Netherlands','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1158,'New Caledonia (France)','CFP franc','XPF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1159,'New Zealand','New Zealand dollar','NZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1160,'Nicaragua','Nicaraguan cordoba','NIO','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1161,'Niger','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1162,'Nigeria','Nigerian naira','NGN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1163,'Niue (New Zealand)','New Zealand dollar','NZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1164,'Norfolk Island (Australia)','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1165,'Northern Mariana Islands (USA)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1166,'North Korea','North Korean won','KPW','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1167,'North Macedonia (formerly Macedonia)','Macedonian denar','MKD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1168,'Norway','Norwegian krone','NOK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1169,'Oman','Omani rial','OMR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1170,'Pakistan','Pakistani rupee','PKR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1171,'Palau','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1172,'Palestine','Israeli new shekel','ILS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1173,'Panama','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1174,'Papua New Guinea','Papua New Guinean kina','PGK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1175,'Paraguay','Paraguayan guarani','PYG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1176,'Peru','Peruvian sol','PEN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1177,'Philippines','Philippine peso','PHP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1178,'Pitcairn Islands (UK)','New Zealand dollar','NZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1179,'Poland','Polish zloty','PLN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1180,'Portugal','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1181,'Puerto Rico (USA)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1182,'Qatar','Qatari riyal','QAR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1183,'Reunion (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1184,'Romania','Romanian leu','RON','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1185,'Russia','Russian ruble','RUB','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1186,'Rwanda','Rwandan franc','RWF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1187,'Saba (Netherlands)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1188,'Saint Barthelemy (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1189,'Saint Helena (UK)','Saint Helena pound','SHP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1190,'Saint Kitts and Nevis','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1191,'Saint Lucia','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1192,'Saint Martin (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1193,'Saint Pierre and Miquelon (France)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1194,'Saint Vincent and the Grenadines','East Caribbean dollar','XCD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1195,'Samoa','Samoan tala','WST','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1196,'San Marino','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1197,'Sao Tome and Principe','Sao Tome and Principe dobra','STN','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1198,'Saudi Arabia','Saudi Arabian riyal','SAR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1199,'Senegal','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1200,'Serbia','Serbian dinar','RSD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1201,'Seychelles','Seychellois rupee','SCR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1202,'Sierra Leone','Sierra Leonean leone','SLL','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1203,'Singapore','Singapore dollar','SGD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1204,'Sint Eustatius (Netherlands)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1205,'Sint Maarten (Netherlands)','Netherlands Antillean guilder','ANG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1206,'Slovakia','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1207,'Slovenia','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1208,'Solomon Islands','Solomon Islands dollar','SBD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1209,'Somalia','Somali shilling','SOS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1210,'South Africa','South African rand','ZAR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1211,'South Georgia Island (UK)','Pound sterling','GBP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1212,'South Korea','South Korean won','KRW','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1213,'South Sudan','South Sudanese pound','SSP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1214,'Spain','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1215,'Sri Lanka','Sri Lankan rupee','LKR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1216,'Sudan','Sudanese pound','SDG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1217,'Suriname','Surinamese dollar','SRD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1218,'Svalbard and Jan Mayen (Norway)','Norwegian krone','NOK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1219,'Sweden','Swedish krona','SEK','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1220,'Switzerland','Swiss franc','CHF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1221,'Syria','Syrian pound','SYP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1222,'Taiwan','New Taiwan dollar','TWD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1223,'Tajikistan','Tajikistani somoni','TJS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1224,'Tanzania','Tanzanian shilling','TZS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1225,'Thailand','Thai baht','THB','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1226,'Timor-Leste','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1227,'Togo','West African CFA franc','XOF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1228,'Tokelau (New Zealand)','New Zealand dollar','NZD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1229,'Tonga','Tongan pa’anga','TOP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1230,'Trinidad and Tobago','Trinidad and Tobago dollar','TTD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1231,'Tristan da Cunha (UK)','Pound sterling','GBP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1232,'Tunisia','Tunisian dinar','TND','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1233,'Turkey','Turkish lira','TRY','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1234,'Turkmenistan','Turkmen manat','TMT','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1235,'Turks and Caicos Islands (UK)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1236,'Tuvalu','Australian dollar','AUD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1237,'Uganda','Ugandan shilling','UGX','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1238,'Ukraine','Ukrainian hryvnia','UAH','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1239,'United Arab Emirates','UAE dirham','AED','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1240,'United Kingdom','Pound sterling','GBP','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1241,'United States of America','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1242,'Uruguay','Uruguayan peso','UYU','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1243,'US Virgin Islands (USA)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1244,'Uzbekistan','Uzbekistani som','UZS','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1245,'Vanuatu','Vanuatu vatu','VUV','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1246,'Vatican City (1Holy See)','European euro','EUR','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1247,'Venezuela','Venezuelan bolivar','VES','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1248,'Vietnam','Vietnamese dong','VND','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1249,'Wake Island (USA)','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1250,'Wallis and Futuna (France)','CFP franc','XPF','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1251,'Yemen','Yemeni rial','YER','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1252,'Zambia','Zambian kwacha','ZMW','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1253,'Zimbabwe','United States dollar','USD','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1254,'','Золото','XAU','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1255,'','Серебро','XAG','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1256,'','Платина','XPT','ru');
INSERT INTO currency(id,country,currency,code,lang) VALUES (1257,'','Палладий','XPD','ru');

############### UKRAINIAN ###############
# TASK: Translate to Ukrainian

INSERT INTO currency(id,country,currency,code,lang) VALUES (2001,'Afghanistan','Afghan afghani','AFN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2002,'Akrotiri and Dhekelia (UK)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2003,'Aland Islands (Finland)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2004,'Albania','Albanian lek','ALL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2005,'Algeria','Algerian dinar','DZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2006,'American Samoa (USA)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2007,'Andorra','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2008,'Angola','Angolan kwanza','AOA','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2009,'Anguilla (UK)','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2010,'Antigua and Barbuda','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2011,'Argentina','Argentine peso','ARS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2012,'Armenia','Armenian dram','AMD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2013,'Aruba (Netherlands)','Aruban florin','AWG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2014,'Ascension Island (UK)','Saint Helena pound','SHP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2015,'Australia','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2016,'Austria','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2017,'Azerbaijan','Azerbaijan manat','AZN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2018,'Bahamas','Bahamian dollar','BSD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2019,'Bahrain','Bahraini dinar','BHD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2020,'Bangladesh','Bangladeshi taka','BDT','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2021,'Barbados','Barbadian dollar','BBD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2022,'Belarus','Belarusian ruble','BYN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2023,'Belgium','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2024,'Belize','Belize dollar','BZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2025,'Benin','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2026,'Bermuda (UK)','Bermudian dollar','BMD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2027,'Bhutan','Bhutanese ngultrum','BTN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2028,'Bolivia','Bolivian boliviano','BOB','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2029,'Bonaire (Netherlands)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2030,'Bosnia and Herzegovina','Bosnia and Herzegovina convertible mark','BAM','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2031,'Botswana','Botswana pula','BWP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2032,'Brazil','Brazilian real','BRL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2033,'British Indian Ocean Territory (UK)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2034,'British Virgin Islands (UK)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2035,'Brunei','Brunei dollar','BND','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2036,'Bulgaria','Bulgarian lev','BGN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2037,'Burkina Faso','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2038,'Burundi','Burundi franc','BIF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2039,'Cabo Verde','Cape Verdean escudo','CVE','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2040,'Cambodia','Cambodian riel','KHR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2041,'Cameroon','Central African CFA franc','XAF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2042,'Canada','Canadian dollar','CAD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2043,'Caribbean Netherlands (Netherlands)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2044,'Cayman Islands (UK)','Cayman Islands dollar','KYD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2045,'Central African Republic','Central African CFA franc','XAF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2046,'Chad','Central African CFA franc','XAF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2047,'Chatham Islands (New Zealand)','New Zealand dollar','NZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2048,'Chile','Chilean peso','CLP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2049,'China','Chinese Yuan Renminbi','CNY','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2050,'Christmas Island (Australia)','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2051,'Cocos (10Keeling) Islands (Australia)','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2052,'Colombia','Colombian peso','COP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2053,'Comoros','Comorian franc','KMF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2054,'Congo, Democratic Republic of the','Congolese franc','CDF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2055,'Congo, Republic of the','Central African CFA franc','XAF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2056,'Cook Islands (New Zealand)','Cook Islands dollar','---','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2057,'Costa Rica','Costa Rican colon','CRC','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2058,'Cote d''Ivoire','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2059,'Croatia','Croatian kuna','HRK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2060,'Cuba','Cuban peso','CUP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2061,'Curacao (Netherlands)','Netherlands Antillean guilder','ANG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2062,'Cyprus','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2063,'Czechia','Czech koruna','CZK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2064,'Denmark','Danish krone','DKK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2065,'Djibouti','Djiboutian franc','DJF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2066,'Dominica','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2067,'Dominican Republic','Dominican peso','DOP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2068,'Ecuador','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2069,'Egypt','Egyptian pound','EGP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2070,'El Salvador','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2071,'Equatorial Guinea','Central African CFA franc','XAF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2072,'Eritrea','Eritrean nakfa','ERN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2073,'Estonia','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2074,'Eswatini (formerly Swaziland)','Swazi lilangeni','SZL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2075,'Ethiopia','Ethiopian birr','ETB','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2076,'Falkland Islands (UK)','Falkland Islands pound','FKP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2077,'Faroe Islands (Denmark)','Faroese krona','---','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2078,'Fiji','Fijian dollar','FJD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2079,'Finland','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2080,'France','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2081,'French Guiana (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2082,'French Polynesia (France)','CFP franc','XPF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2083,'Gabon','Central African CFA franc','XAF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2084,'Gambia','Gambian dalasi','GMD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2085,'Georgia','Georgian lari','GEL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2086,'Germany','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2087,'Ghana','Ghanaian cedi','GHS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2088,'Gibraltar (UK)','Gibraltar pound','GIP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2089,'Greece','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2090,'Greenland (Denmark)','Danish krone','DKK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2091,'Grenada','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2092,'Guadeloupe (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2093,'Guam (USA)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2094,'Guatemala','Guatemalan quetzal','GTQ','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2095,'Guernsey (UK)','Guernsey Pound','GGP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2096,'Guinea','Guinean franc','GNF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2097,'Guinea-Bissau','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2098,'Guyana','Guyanese dollar','GYD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2099,'Haiti','Haitian gourde','HTG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2100,'Honduras','Honduran lempira','HNL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2101,'Hong Kong (China)','Hong Kong dollar','HKD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2102,'Hungary','Hungarian forint','HUF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2103,'Iceland','Icelandic krona','ISK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2104,'India','Indian rupee','INR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2105,'Indonesia','Indonesian rupiah','IDR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2106,'International Monetary Fund (1IMF)','SDR (1Special Drawing Right)','XDR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2107,'Iran','Iranian rial','IRR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2108,'Iraq','Iraqi dinar','IQD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2109,'Ireland','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2110,'Isle of Man (UK)','Manx pound','IMP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2111,'Israel','Israeli new shekel','ILS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2112,'Italy','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2113,'Jamaica','Jamaican dollar','JMD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2114,'Japan','Japanese yen','JPY','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2115,'Jersey (UK)','Jersey pound','JEP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2116,'Jordan','Jordanian dinar','JOD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2117,'Kazakhstan','Kazakhstani tenge','KZT','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2118,'Kenya','Kenyan shilling','KES','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2119,'Kiribati','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2120,'Kosovo','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2121,'Kuwait','Kuwaiti dinar','KWD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2122,'Kyrgyzstan','Kyrgyzstani som','KGS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2123,'Laos','Lao kip','LAK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2124,'Latvia','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2125,'Lebanon','Lebanese pound','LBP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2126,'Lesotho','Lesotho loti','LSL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2127,'Liberia','Liberian dollar','LRD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2128,'Libya','Libyan dinar','LYD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2129,'Liechtenstein','Swiss franc','CHF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2130,'Lithuania','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2131,'Luxembourg','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2132,'Macau (China)','Macanese pataca','MOP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2133,'Madagascar','Malagasy ariary','MGA','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2134,'Malawi','Malawian kwacha','MWK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2135,'Malaysia','Malaysian ringgit','MYR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2136,'Maldives','Maldivian rufiyaa','MVR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2137,'Mali','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2138,'Malta','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2139,'Marshall Islands','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2140,'Martinique (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2141,'Mauritania','Mauritanian ouguiya','MRU','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2142,'Mauritius','Mauritian rupee','MUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2143,'Mayotte (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2144,'Mexico','Mexican peso','MXN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2145,'Micronesia','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2146,'Moldova','Moldovan leu','MDL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2147,'Monaco','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2148,'Mongolia','Mongolian tugrik','MNT','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2149,'Montenegro','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2150,'Montserrat (UK)','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2151,'Morocco','Moroccan dirham','MAD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2152,'Mozambique','Mozambican metical','MZN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2153,'Myanmar (formerly Burma)','Myanmar kyat','MMK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2154,'Namibia','Namibian dollar','NAD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2155,'Nauru','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2156,'Nepal','Nepalese rupee','NPR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2157,'Netherlands','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2158,'New Caledonia (France)','CFP franc','XPF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2159,'New Zealand','New Zealand dollar','NZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2160,'Nicaragua','Nicaraguan cordoba','NIO','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2161,'Niger','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2162,'Nigeria','Nigerian naira','NGN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2163,'Niue (New Zealand)','New Zealand dollar','NZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2164,'Norfolk Island (Australia)','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2165,'Northern Mariana Islands (USA)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2166,'North Korea','North Korean won','KPW','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2167,'North Macedonia (formerly Macedonia)','Macedonian denar','MKD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2168,'Norway','Norwegian krone','NOK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2169,'Oman','Omani rial','OMR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2170,'Pakistan','Pakistani rupee','PKR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2171,'Palau','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2172,'Palestine','Israeli new shekel','ILS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2173,'Panama','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2174,'Papua New Guinea','Papua New Guinean kina','PGK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2175,'Paraguay','Paraguayan guarani','PYG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2176,'Peru','Peruvian sol','PEN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2177,'Philippines','Philippine peso','PHP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2178,'Pitcairn Islands (UK)','New Zealand dollar','NZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2179,'Poland','Polish zloty','PLN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2180,'Portugal','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2181,'Puerto Rico (USA)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2182,'Qatar','Qatari riyal','QAR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2183,'Reunion (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2184,'Romania','Romanian leu','RON','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2185,'Russia','Russian ruble','RUB','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2186,'Rwanda','Rwandan franc','RWF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2187,'Saba (Netherlands)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2188,'Saint Barthelemy (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2189,'Saint Helena (UK)','Saint Helena pound','SHP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2190,'Saint Kitts and Nevis','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2191,'Saint Lucia','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2192,'Saint Martin (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2193,'Saint Pierre and Miquelon (France)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2194,'Saint Vincent and the Grenadines','East Caribbean dollar','XCD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2195,'Samoa','Samoan tala','WST','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2196,'San Marino','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2197,'Sao Tome and Principe','Sao Tome and Principe dobra','STN','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2198,'Saudi Arabia','Saudi Arabian riyal','SAR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2199,'Senegal','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2200,'Serbia','Serbian dinar','RSD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2201,'Seychelles','Seychellois rupee','SCR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2202,'Sierra Leone','Sierra Leonean leone','SLL','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2203,'Singapore','Singapore dollar','SGD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2204,'Sint Eustatius (Netherlands)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2205,'Sint Maarten (Netherlands)','Netherlands Antillean guilder','ANG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2206,'Slovakia','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2207,'Slovenia','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2208,'Solomon Islands','Solomon Islands dollar','SBD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2209,'Somalia','Somali shilling','SOS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2210,'South Africa','South African rand','ZAR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2211,'South Georgia Island (UK)','Pound sterling','GBP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2212,'South Korea','South Korean won','KRW','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2213,'South Sudan','South Sudanese pound','SSP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2214,'Spain','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2215,'Sri Lanka','Sri Lankan rupee','LKR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2216,'Sudan','Sudanese pound','SDG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2217,'Suriname','Surinamese dollar','SRD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2218,'Svalbard and Jan Mayen (Norway)','Norwegian krone','NOK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2219,'Sweden','Swedish krona','SEK','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2220,'Switzerland','Swiss franc','CHF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2221,'Syria','Syrian pound','SYP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2222,'Taiwan','New Taiwan dollar','TWD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2223,'Tajikistan','Tajikistani somoni','TJS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2224,'Tanzania','Tanzanian shilling','TZS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2225,'Thailand','Thai baht','THB','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2226,'Timor-Leste','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2227,'Togo','West African CFA franc','XOF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2228,'Tokelau (New Zealand)','New Zealand dollar','NZD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2229,'Tonga','Tongan pa’anga','TOP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2230,'Trinidad and Tobago','Trinidad and Tobago dollar','TTD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2231,'Tristan da Cunha (UK)','Pound sterling','GBP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2232,'Tunisia','Tunisian dinar','TND','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2233,'Turkey','Turkish lira','TRY','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2234,'Turkmenistan','Turkmen manat','TMT','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2235,'Turks and Caicos Islands (UK)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2236,'Tuvalu','Австралійський долар','AUD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2237,'Uganda','Ugandan shilling','UGX','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2238,'Ukraine','Ukrainian hryvnia','UAH','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2239,'United Arab Emirates','UAE dirham','AED','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2240,'United Kingdom','Pound sterling','GBP','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2241,'United States of America','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2242,'Uruguay','Uruguayan peso','UYU','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2243,'US Virgin Islands (USA)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2244,'Uzbekistan','Uzbekistani som','UZS','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2245,'Vanuatu','Vanuatu vatu','VUV','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2246,'Vatican City (1Holy See)','European euro','EUR','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2247,'Venezuela','Venezuelan bolivar','VES','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2248,'Vietnam','Vietnamese dong','VND','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2249,'Wake Island (USA)','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2250,'Wallis and Futuna (France)','CFP franc','XPF','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2251,'Yemen','Yemeni rial','YER','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2252,'Zambia','Zambian kwacha','ZMW','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2253,'Zimbabwe','United States dollar','USD','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2254,'','Золото','XAU','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2255,'','Срібло','XAG','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2256,'','Платіна','XPT','uk');
INSERT INTO currency(id,country,currency,code,lang) VALUES (2257,'','Паладій','XPD','uk');