CREATE DATABASE finance CHARACTER SET utf8 COLLATE utf8_general_ci;
create user finance_user@localhost;
set password for finance_user@localhost=password('psw_finance_user');
grant all on finance.* to finance_user@localhost with grant option;

use finance;

CREATE TABLE bankua (
id INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
code VARCHAR(7) NOT NULL,
exchangedate DATE NOT NULL,
rate float UNSIGNED
);

# ISO 4217 Currency Codes for different languages e.g, USD = United States dollar


CREATE TABLE currency(
id       INTEGER  NOT NULL PRIMARY KEY,
country  VARCHAR(100) NOT NULL,
currency VARCHAR(100) NOT NULL,
code     VARCHAR(3) NOT NULL,
lang VARCHAR(2) NOT NULL
);


INSERT INTO `currency` (`id`, `country`, `currency`, `code`, `lang`) VALUES
(1, 'Afghanistan', 'Afghan afghani', 'AFN', 'en'),
(2, 'Akrotiri and Dhekelia (UK)', 'European euro', 'EUR', 'en'),
(3, 'Aland Islands (Finland)', 'European euro', 'EUR', 'en'),
(4, 'Albania', 'Albanian lek', 'ALL', 'en'),
(5, 'Algeria', 'Algerian dinar', 'DZD', 'en'),
(6, 'American Samoa (USA)', 'United States dollar', 'USD', 'en'),
(7, 'Andorra', 'European euro', 'EUR', 'en'),
(8, 'Angola', 'Angolan kwanza', 'AOA', 'en'),
(9, 'Anguilla (UK)', 'East Caribbean dollar', 'XCD', 'en'),
(10, 'Antigua and Barbuda', 'East Caribbean dollar', 'XCD', 'en'),
(11, 'Argentina', 'Argentine peso', 'ARS', 'en'),
(12, 'Armenia', 'Armenian dram', 'AMD', 'en'),
(13, 'Aruba (Netherlands)', 'Aruban florin', 'AWG', 'en'),
(14, 'Ascension Island (UK)', 'Saint Helena pound', 'SHP', 'en'),
(15, 'Australia', 'Australian dollar', 'AUD', 'en'),
(16, 'Austria', 'European euro', 'EUR', 'en'),
(17, 'Azerbaijan', 'Azerbaijan manat', 'AZN', 'en'),
(18, 'Bahamas', 'Bahamian dollar', 'BSD', 'en'),
(19, 'Bahrain', 'Bahraini dinar', 'BHD', 'en'),
(20, 'Bangladesh', 'Bangladeshi taka', 'BDT', 'en'),
(21, 'Barbados', 'Barbadian dollar', 'BBD', 'en'),
(22, 'Belarus', 'Belarusian ruble', 'BYN', 'en'),
(23, 'Belgium', 'European euro', 'EUR', 'en'),
(24, 'Belize', 'Belize dollar', 'BZD', 'en'),
(25, 'Benin', 'West African CFA franc', 'XOF', 'en'),
(26, 'Bermuda (UK)', 'Bermudian dollar', 'BMD', 'en'),
(27, 'Bhutan', 'Bhutanese ngultrum', 'BTN', 'en'),
(28, 'Bolivia', 'Bolivian boliviano', 'BOB', 'en'),
(29, 'Bonaire (Netherlands)', 'United States dollar', 'USD', 'en'),
(30, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark', 'BAM', 'en'),
(31, 'Botswana', 'Botswana pula', 'BWP', 'en'),
(32, 'Brazil', 'Brazilian real', 'BRL', 'en'),
(33, 'British Indian Ocean Territory (UK)', 'United States dollar', 'USD', 'en'),
(34, 'British Virgin Islands (UK)', 'United States dollar', 'USD', 'en'),
(35, 'Brunei', 'Brunei dollar', 'BND', 'en'),
(36, 'Bulgaria', 'Bulgarian lev', 'BGN', 'en'),
(37, 'Burkina Faso', 'West African CFA franc', 'XOF', 'en'),
(38, 'Burundi', 'Burundi franc', 'BIF', 'en'),
(39, 'Cabo Verde', 'Cape Verdean escudo', 'CVE', 'en'),
(40, 'Cambodia', 'Cambodian riel', 'KHR', 'en'),
(41, 'Cameroon', 'Central African CFA franc', 'XAF', 'en'),
(42, 'Canada', 'Canadian dollar', 'CAD', 'en'),
(43, 'Caribbean Netherlands (Netherlands)', 'United States dollar', 'USD', 'en'),
(44, 'Cayman Islands (UK)', 'Cayman Islands dollar', 'KYD', 'en'),
(45, 'Central African Republic', 'Central African CFA franc', 'XAF', 'en'),
(46, 'Chad', 'Central African CFA franc', 'XAF', 'en'),
(47, 'Chatham Islands (New Zealand)', 'New Zealand dollar', 'NZD', 'en'),
(48, 'Chile', 'Chilean peso', 'CLP', 'en'),
(49, 'China', 'Chinese Yuan Renminbi', 'CNY', 'en'),
(50, 'Christmas Island (Australia)', 'Australian dollar', 'AUD', 'en'),
(51, 'Cocos (Keeling) Islands (Australia)', 'Australian dollar', 'AUD', 'en'),
(52, 'Colombia', 'Colombian peso', 'COP', 'en'),
(53, 'Comoros', 'Comorian franc', 'KMF', 'en'),
(54, 'Congo, Democratic Republic of the', 'Congolese franc', 'CDF', 'en'),
(55, 'Congo, Republic of the', 'Central African CFA franc', 'XAF', 'en'),
(56, 'Cook Islands (New Zealand)', 'Cook Islands dollar', '---', 'en'),
(57, 'Costa Rica', 'Costa Rican colon', 'CRC', 'en'),
(58, 'Cote d\'Ivoire', 'West African CFA franc', 'XOF', 'en'),
(59, 'Croatia', 'Croatian kuna', 'HRK', 'en'),
(60, 'Cuba', 'Cuban peso', 'CUP', 'en'),
(61, 'Curacao (Netherlands)', 'Netherlands Antillean guilder', 'ANG', 'en'),
(62, 'Cyprus', 'European euro', 'EUR', 'en'),
(63, 'Czechia', 'Czech koruna', 'CZK', 'en'),
(64, 'Denmark', 'Danish krone', 'DKK', 'en'),
(65, 'Djibouti', 'Djiboutian franc', 'DJF', 'en'),
(66, 'Dominica', 'East Caribbean dollar', 'XCD', 'en'),
(67, 'Dominican Republic', 'Dominican peso', 'DOP', 'en'),
(68, 'Ecuador', 'United States dollar', 'USD', 'en'),
(69, 'Egypt', 'Egyptian pound', 'EGP', 'en'),
(70, 'El Salvador', 'United States dollar', 'USD', 'en'),
(71, 'Equatorial Guinea', 'Central African CFA franc', 'XAF', 'en'),
(72, 'Eritrea', 'Eritrean nakfa', 'ERN', 'en'),
(73, 'Estonia', 'European euro', 'EUR', 'en'),
(74, 'Eswatini (formerly Swaziland)', 'Swazi lilangeni', 'SZL', 'en'),
(75, 'Ethiopia', 'Ethiopian birr', 'ETB', 'en'),
(76, 'Falkland Islands (UK)', 'Falkland Islands pound', 'FKP', 'en'),
(77, 'Faroe Islands (Denmark)', 'Faroese krona', '---', 'en'),
(78, 'Fiji', 'Fijian dollar', 'FJD', 'en'),
(79, 'Finland', 'European euro', 'EUR', 'en'),
(80, 'France', 'European euro', 'EUR', 'en'),
(81, 'French Guiana (France)', 'European euro', 'EUR', 'en'),
(82, 'French Polynesia (France)', 'CFP franc', 'XPF', 'en'),
(83, 'Gabon', 'Central African CFA franc', 'XAF', 'en'),
(84, 'Gambia', 'Gambian dalasi', 'GMD', 'en'),
(85, 'Georgia', 'Georgian lari', 'GEL', 'en'),
(86, 'Germany', 'European euro', 'EUR', 'en'),
(87, 'Ghana', 'Ghanaian cedi', 'GHS', 'en'),
(88, 'Gibraltar (UK)', 'Gibraltar pound', 'GIP', 'en'),
(89, 'Greece', 'European euro', 'EUR', 'en'),
(90, 'Greenland (Denmark)', 'Danish krone', 'DKK', 'en'),
(91, 'Grenada', 'East Caribbean dollar', 'XCD', 'en'),
(92, 'Guadeloupe (France)', 'European euro', 'EUR', 'en'),
(93, 'Guam (USA)', 'United States dollar', 'USD', 'en'),
(94, 'Guatemala', 'Guatemalan quetzal', 'GTQ', 'en'),
(95, 'Guernsey (UK)', 'Guernsey Pound', 'GGP', 'en'),
(96, 'Guinea', 'Guinean franc', 'GNF', 'en'),
(97, 'Guinea-Bissau', 'West African CFA franc', 'XOF', 'en'),
(98, 'Guyana', 'Guyanese dollar', 'GYD', 'en'),
(99, 'Haiti', 'Haitian gourde', 'HTG', 'en'),
(100, 'Honduras', 'Honduran lempira', 'HNL', 'en'),
(101, 'Hong Kong (China)', 'Hong Kong dollar', 'HKD', 'en'),
(102, 'Hungary', 'Hungarian forint', 'HUF', 'en'),
(103, 'Iceland', 'Icelandic krona', 'ISK', 'en'),
(104, 'India', 'Indian rupee', 'INR', 'en'),
(105, 'Indonesia', 'Indonesian rupiah', 'IDR', 'en'),
(106, 'International Monetary Fund (IMF)', 'SDR (Special Drawing Right)', 'XDR', 'en'),
(107, 'Iran', 'Iranian rial', 'IRR', 'en'),
(108, 'Iraq', 'Iraqi dinar', 'IQD', 'en'),
(109, 'Ireland', 'European euro', 'EUR', 'en'),
(110, 'Isle of Man (UK)', 'Manx pound', 'IMP', 'en'),
(111, 'Israel', 'Israeli new shekel', 'ILS', 'en'),
(112, 'Italy', 'European euro', 'EUR', 'en'),
(113, 'Jamaica', 'Jamaican dollar', 'JMD', 'en'),
(114, 'Japan', 'Japanese yen', 'JPY', 'en'),
(115, 'Jersey (UK)', 'Jersey pound', 'JEP', 'en'),
(116, 'Jordan', 'Jordanian dinar', 'JOD', 'en'),
(117, 'Kazakhstan', 'Kazakhstani tenge', 'KZT', 'en'),
(118, 'Kenya', 'Kenyan shilling', 'KES', 'en'),
(119, 'Kiribati', 'Australian dollar', 'AUD', 'en'),
(120, 'Kosovo', 'European euro', 'EUR', 'en'),
(121, 'Kuwait', 'Kuwaiti dinar', 'KWD', 'en'),
(122, 'Kyrgyzstan', 'Kyrgyzstani som', 'KGS', 'en'),
(123, 'Laos', 'Lao kip', 'LAK', 'en'),
(124, 'Latvia', 'European euro', 'EUR', 'en'),
(125, 'Lebanon', 'Lebanese pound', 'LBP', 'en'),
(126, 'Lesotho', 'Lesotho loti', 'LSL', 'en'),
(127, 'Liberia', 'Liberian dollar', 'LRD', 'en'),
(128, 'Libya', 'Libyan dinar', 'LYD', 'en'),
(129, 'Liechtenstein', 'Swiss franc', 'CHF', 'en'),
(130, 'Lithuania', 'European euro', 'EUR', 'en'),
(131, 'Luxembourg', 'European euro', 'EUR', 'en'),
(132, 'Macau (China)', 'Macanese pataca', 'MOP', 'en'),
(133, 'Madagascar', 'Malagasy ariary', 'MGA', 'en'),
(134, 'Malawi', 'Malawian kwacha', 'MWK', 'en'),
(135, 'Malaysia', 'Malaysian ringgit', 'MYR', 'en'),
(136, 'Maldives', 'Maldivian rufiyaa', 'MVR', 'en'),
(137, 'Mali', 'West African CFA franc', 'XOF', 'en'),
(138, 'Malta', 'European euro', 'EUR', 'en'),
(139, 'Marshall Islands', 'United States dollar', 'USD', 'en'),
(140, 'Martinique (France)', 'European euro', 'EUR', 'en'),
(141, 'Mauritania', 'Mauritanian ouguiya', 'MRU', 'en'),
(142, 'Mauritius', 'Mauritian rupee', 'MUR', 'en'),
(143, 'Mayotte (France)', 'European euro', 'EUR', 'en'),
(144, 'Mexico', 'Mexican peso', 'MXN', 'en'),
(145, 'Micronesia', 'United States dollar', 'USD', 'en'),
(146, 'Moldova', 'Moldovan leu', 'MDL', 'en'),
(147, 'Monaco', 'European euro', 'EUR', 'en'),
(148, 'Mongolia', 'Mongolian tugrik', 'MNT', 'en'),
(149, 'Montenegro', 'European euro', 'EUR', 'en'),
(150, 'Montserrat (UK)', 'East Caribbean dollar', 'XCD', 'en'),
(151, 'Morocco', 'Moroccan dirham', 'MAD', 'en'),
(152, 'Mozambique', 'Mozambican metical', 'MZN', 'en'),
(153, 'Myanmar (formerly Burma)', 'Myanmar kyat', 'MMK', 'en'),
(154, 'Namibia', 'Namibian dollar', 'NAD', 'en'),
(155, 'Nauru', 'Australian dollar', 'AUD', 'en'),
(156, 'Nepal', 'Nepalese rupee', 'NPR', 'en'),
(157, 'Netherlands', 'European euro', 'EUR', 'en'),
(158, 'New Caledonia (France)', 'CFP franc', 'XPF', 'en'),
(159, 'New Zealand', 'New Zealand dollar', 'NZD', 'en'),
(160, 'Nicaragua', 'Nicaraguan cordoba', 'NIO', 'en'),
(161, 'Niger', 'West African CFA franc', 'XOF', 'en'),
(162, 'Nigeria', 'Nigerian naira', 'NGN', 'en'),
(163, 'Niue (New Zealand)', 'New Zealand dollar', 'NZD', 'en'),
(164, 'Norfolk Island (Australia)', 'Australian dollar', 'AUD', 'en'),
(165, 'Northern Mariana Islands (USA)', 'United States dollar', 'USD', 'en'),
(166, 'North Korea', 'North Korean won', 'KPW', 'en'),
(167, 'North Macedonia (formerly Macedonia)', 'Macedonian denar', 'MKD', 'en'),
(168, 'Norway', 'Norwegian krone', 'NOK', 'en'),
(169, 'Oman', 'Omani rial', 'OMR', 'en'),
(170, 'Pakistan', 'Pakistani rupee', 'PKR', 'en'),
(171, 'Palau', 'United States dollar', 'USD', 'en'),
(172, 'Palestine', 'Israeli new shekel', 'ILS', 'en'),
(173, 'Panama', 'United States dollar', 'USD', 'en'),
(174, 'Papua New Guinea', 'Papua New Guinean kina', 'PGK', 'en'),
(175, 'Paraguay', 'Paraguayan guarani', 'PYG', 'en'),
(176, 'Peru', 'Peruvian sol', 'PEN', 'en'),
(177, 'Philippines', 'Philippine peso', 'PHP', 'en'),
(178, 'Pitcairn Islands (UK)', 'New Zealand dollar', 'NZD', 'en'),
(179, 'Poland', 'Polish zloty', 'PLN', 'en'),
(180, 'Portugal', 'European euro', 'EUR', 'en'),
(181, 'Puerto Rico (USA)', 'United States dollar', 'USD', 'en'),
(182, 'Qatar', 'Qatari riyal', 'QAR', 'en'),
(183, 'Reunion (France)', 'European euro', 'EUR', 'en'),
(184, 'Romania', 'Romanian leu', 'RON', 'en'),
(185, 'Russia', 'Russian ruble', 'RUB', 'en'),
(186, 'Rwanda', 'Rwandan franc', 'RWF', 'en'),
(187, 'Saba (Netherlands)', 'United States dollar', 'USD', 'en'),
(188, 'Saint Barthelemy (France)', 'European euro', 'EUR', 'en'),
(189, 'Saint Helena (UK)', 'Saint Helena pound', 'SHP', 'en'),
(190, 'Saint Kitts and Nevis', 'East Caribbean dollar', 'XCD', 'en'),
(191, 'Saint Lucia', 'East Caribbean dollar', 'XCD', 'en'),
(192, 'Saint Martin (France)', 'European euro', 'EUR', 'en'),
(193, 'Saint Pierre and Miquelon (France)', 'European euro', 'EUR', 'en'),
(194, 'Saint Vincent and the Grenadines', 'East Caribbean dollar', 'XCD', 'en'),
(195, 'Samoa', 'Samoan tala', 'WST', 'en'),
(196, 'San Marino', 'European euro', 'EUR', 'en'),
(197, 'Sao Tome and Principe', 'Sao Tome and Principe dobra', 'STN', 'en'),
(198, 'Saudi Arabia', 'Saudi Arabian riyal', 'SAR', 'en'),
(199, 'Senegal', 'West African CFA franc', 'XOF', 'en'),
(200, 'Serbia', 'Serbian dinar', 'RSD', 'en'),
(201, 'Seychelles', 'Seychellois rupee', 'SCR', 'en'),
(202, 'Sierra Leone', 'Sierra Leonean leone', 'SLL', 'en'),
(203, 'Singapore', 'Singapore dollar', 'SGD', 'en'),
(204, 'Sint Eustatius (Netherlands)', 'United States dollar', 'USD', 'en'),
(205, 'Sint Maarten (Netherlands)', 'Netherlands Antillean guilder', 'ANG', 'en'),
(206, 'Slovakia', 'European euro', 'EUR', 'en'),
(207, 'Slovenia', 'European euro', 'EUR', 'en'),
(208, 'Solomon Islands', 'Solomon Islands dollar', 'SBD', 'en'),
(209, 'Somalia', 'Somali shilling', 'SOS', 'en'),
(210, 'South Africa', 'South African rand', 'ZAR', 'en'),
(211, 'South Georgia Island (UK)', 'Pound sterling', 'GBP', 'en'),
(212, 'South Korea', 'South Korean won', 'KRW', 'en'),
(213, 'South Sudan', 'South Sudanese pound', 'SSP', 'en'),
(214, 'Spain', 'European euro', 'EUR', 'en'),
(215, 'Sri Lanka', 'Sri Lankan rupee', 'LKR', 'en'),
(216, 'Sudan', 'Sudanese pound', 'SDG', 'en'),
(217, 'Suriname', 'Surinamese dollar', 'SRD', 'en'),
(218, 'Svalbard and Jan Mayen (Norway)', 'Norwegian krone', 'NOK', 'en'),
(219, 'Sweden', 'Swedish krona', 'SEK', 'en'),
(220, 'Switzerland', 'Swiss franc', 'CHF', 'en'),
(221, 'Syria', 'Syrian pound', 'SYP', 'en'),
(222, 'Taiwan', 'New Taiwan dollar', 'TWD', 'en'),
(223, 'Tajikistan', 'Tajikistani somoni', 'TJS', 'en'),
(224, 'Tanzania', 'Tanzanian shilling', 'TZS', 'en'),
(225, 'Thailand', 'Thai baht', 'THB', 'en'),
(226, 'Timor-Leste', 'United States dollar', 'USD', 'en'),
(227, 'Togo', 'West African CFA franc', 'XOF', 'en'),
(228, 'Tokelau (New Zealand)', 'New Zealand dollar', 'NZD', 'en'),
(229, 'Tonga', 'Tongan pa’anga', 'TOP', 'en'),
(230, 'Trinidad and Tobago', 'Trinidad and Tobago dollar', 'TTD', 'en'),
(231, 'Tristan da Cunha (UK)', 'Pound sterling', 'GBP', 'en'),
(232, 'Tunisia', 'Tunisian dinar', 'TND', 'en'),
(233, 'Turkey', 'Turkish lira', 'TRY', 'en'),
(234, 'Turkmenistan', 'Turkmen manat', 'TMT', 'en'),
(235, 'Turks and Caicos Islands (UK)', 'United States dollar', 'USD', 'en'),
(236, 'Tuvalu', 'Australian dollar', 'AUD', 'en'),
(237, 'Uganda', 'Ugandan shilling', 'UGX', 'en'),
(238, 'Ukraine', 'Ukrainian hryvnia', 'UAH', 'en'),
(239, 'United Arab Emirates', 'UAE dirham', 'AED', 'en'),
(240, 'United Kingdom', 'Pound sterling', 'GBP', 'en'),
(241, 'United States of America', 'United States dollar', 'USD', 'en'),
(242, 'Uruguay', 'Uruguayan peso', 'UYU', 'en'),
(243, 'US Virgin Islands (USA)', 'United States dollar', 'USD', 'en'),
(244, 'Uzbekistan', 'Uzbekistani som', 'UZS', 'en'),
(245, 'Vanuatu', 'Vanuatu vatu', 'VUV', 'en'),
(246, 'Vatican City (Holy See)', 'European euro', 'EUR', 'en'),
(247, 'Venezuela', 'Venezuelan bolivar', 'VES', 'en'),
(248, 'Vietnam', 'Vietnamese dong', 'VND', 'en'),
(249, 'Wake Island (USA)', 'United States dollar', 'USD', 'en'),
(250, 'Wallis and Futuna (France)', 'CFP franc', 'XPF', 'en'),
(251, 'Yemen', 'Yemeni rial', 'YER', 'en'),
(252, 'Zambia', 'Zambian kwacha', 'ZMW', 'en'),
(253, 'Zimbabwe', 'United States dollar', 'USD', 'en'),
(254, '', 'Gold', 'XAU', 'en'),
(255, '', 'Silver', 'XAG', 'en'),
(256, '', 'Platinum', 'XPT', 'en'),
(257, '', 'Palladium', 'XPD', 'en'),
(1001, 'Afghanistan', 'Афгани', 'AFN', 'ru'),
(1002, 'Akrotiri and Dhekelia (UK)', 'Евро', 'EUR', 'ru'),
(1003, 'Aland Islands (Finland)', 'Евро', 'EUR', 'ru'),
(1004, 'Albania', 'Албанский лек', 'ALL', 'ru'),
(1005, 'Algeria', 'Алжирский динар', 'DZD', 'ru'),
(1006, 'American Samoa (USA)', 'Доллар США', 'USD', 'ru'),
(1007, 'Andorra', 'Евро', 'EUR', 'ru'),
(1008, 'Angola', 'Ангольская кванза', 'AOA', 'ru'),
(1009, 'Anguilla (UK)', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1010, 'Antigua and Barbuda', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1011, 'Argentina', 'Аргентинское песо', 'ARS', 'ru'),
(1012, 'Armenia', 'Армянский драм', 'AMD', 'ru'),
(1013, 'Aruba (Netherlands)', 'Арубанский флорин', 'AWG', 'ru'),
(1014, 'Ascension Island (UK)', 'Фунт острова Святой Елены', 'SHP', 'ru'),
(1015, 'Australia', 'Австралийский доллар', 'AUD', 'ru'),
(1016, 'Austria', 'Евро', 'EUR', 'ru'),
(1017, 'Azerbaijan', 'Азербайджанский манат', 'AZN', 'ru'),
(1018, 'Bahamas', 'Багамский доллар', 'BSD', 'ru'),
(1019, 'Bahrain', 'Бахрейнский динар', 'BHD', 'ru'),
(1020, 'Bangladesh', 'Бангладешская така', 'BDT', 'ru'),
(1021, 'Barbados', 'Барбадосский доллар', 'BBD', 'ru'),
(1022, 'Belarus', 'Белорусский рубль', 'BYN', 'ru'),
(1023, 'Belgium', 'Евро', 'EUR', 'ru'),
(1024, 'Belize', 'Белизский доллар', 'BZD', 'ru'),
(1025, 'Benin', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1026, 'Bermuda (UK)', 'Бермудский доллар', 'BMD', 'ru'),
(1027, 'Bhutan', 'Бутанский нгултрум', 'BTN', 'ru'),
(1028, 'Bolivia', 'Боливийский боливиано', 'BOB', 'ru'),
(1029, 'Bonaire (Netherlands)', 'Доллар США', 'USD', 'ru'),
(1030, 'Bosnia and Herzegovina', 'Конвертируемая марка Боснии и Герцеговины', 'BAM', 'ru'),
(1031, 'Botswana', 'Ботсванская пула', 'BWP', 'ru'),
(1032, 'Brazil', 'Бразильский реал', 'BRL', 'ru'),
(1033, 'British Indian Ocean Territory (UK)', 'Доллар США', 'USD', 'ru'),
(1034, 'British Virgin Islands (UK)', 'Доллар США', 'USD', 'ru'),
(1035, 'Brunei', 'Брунейский доллар', 'BND', 'ru'),
(1036, 'Bulgaria', 'Болгарский лев', 'BGN', 'ru'),
(1037, 'Burkina Faso', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1038, 'Burundi', 'Бурундийский франк', 'BIF', 'ru'),
(1039, 'Cabo Verde', 'Эскудо Кабо-Верде', 'CVE', 'ru'),
(1040, 'Cambodia', 'Камбоджийский риель', 'KHR', 'ru'),
(1041, 'Cameroon', 'Франк КФА BEAC', 'XAF', 'ru'),
(1042, 'Canada', 'Канадский доллар', 'CAD', 'ru'),
(1043, 'Caribbean Netherlands (Netherlands)', 'Доллар США', 'USD', 'ru'),
(1044, 'Cayman Islands (UK)', 'Доллар Каймановых островов', 'KYD', 'ru'),
(1045, 'Central African Republic', 'Франк КФА BEAC', 'XAF', 'ru'),
(1046, 'Chad', 'Франк КФА BEAC', 'XAF', 'ru'),
(1047, 'Chatham Islands (New Zealand)', 'Новозеландский доллар', 'NZD', 'ru'),
(1048, 'Chile', 'Чилийское песо', 'CLP', 'ru'),
(1049, 'China', 'Китайский юань', 'CNY', 'ru'),
(1050, 'Christmas Island (Australia)', 'Австралийский доллар', 'AUD', 'ru'),
(1051, 'Cocos (10Keeling) Islands (Australia)', 'Австралийский доллар', 'AUD', 'ru'),
(1052, 'Colombia', 'Колумбийское песо', 'COP', 'ru'),
(1053, 'Comoros', 'Франк Коморских островов', 'KMF', 'ru'),
(1054, 'Congo, Democratic Republic of the', 'Конголезский франк', 'CDF', 'ru'),
(1055, 'Congo, Republic of the', 'Франк КФА BEAC', 'XAF', 'ru'),
(1056, 'Cook Islands (New Zealand)', 'Cook Islands dollar', '---', 'ru'),
(1057, 'Costa Rica', 'Костариканский колон', 'CRC', 'ru'),
(1058, 'Cote d\'Ivoire', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1059, 'Croatia', 'Хорватская куна', 'HRK', 'ru'),
(1060, 'Cuba', 'Кубинское песо', 'CUP', 'ru'),
(1061, 'Curacao (Netherlands)', 'Нидерландский антильский гульден', 'ANG', 'ru'),
(1062, 'Cyprus', 'Евро', 'EUR', 'ru'),
(1063, 'Czechia', 'Чешская крона', 'CZK', 'ru'),
(1064, 'Denmark', 'Датская крона', 'DKK', 'ru'),
(1065, 'Djibouti', 'Франк Джибути', 'DJF', 'ru'),
(1066, 'Dominica', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1067, 'Dominican Republic', 'Доминиканское песо', 'DOP', 'ru'),
(1068, 'Ecuador', 'Доллар США', 'USD', 'ru'),
(1069, 'Egypt', 'Египетский фунт', 'EGP', 'ru'),
(1070, 'El Salvador', 'Доллар США', 'USD', 'ru'),
(1071, 'Equatorial Guinea', 'Франк КФА BEAC', 'XAF', 'ru'),
(1072, 'Eritrea', 'Эритрейская накфа', 'ERN', 'ru'),
(1073, 'Estonia', 'Евро', 'EUR', 'ru'),
(1074, 'Eswatini (formerly Swaziland)', 'Свазилендский лилангени', 'SZL', 'ru'),
(1075, 'Ethiopia', 'Эфиопский быр', 'ETB', 'ru'),
(1076, 'Falkland Islands (UK)', 'Фунт Фолклендских островов', 'FKP', 'ru'),
(1077, 'Faroe Islands (Denmark)', 'Faroese krona', '---', 'ru'),
(1078, 'Fiji', 'Доллар Фиджи', 'FJD', 'ru'),
(1079, 'Finland', 'Евро', 'EUR', 'ru'),
(1080, 'France', 'Евро', 'EUR', 'ru'),
(1081, 'French Guiana (France)', 'Евро', 'EUR', 'ru'),
(1082, 'French Polynesia (France)', 'Французский тихоокеанский франк', 'XPF', 'ru'),
(1083, 'Gabon', 'Франк КФА BEAC', 'XAF', 'ru'),
(1084, 'Gambia', 'Гамбийский даласи', 'GMD', 'ru'),
(1085, 'Georgia', 'Грузинский лари', 'GEL', 'ru'),
(1086, 'Germany', 'Евро', 'EUR', 'ru'),
(1087, 'Ghana', 'Ганский седи', 'GHS', 'ru'),
(1088, 'Gibraltar (UK)', 'Гибралтарский фунт', 'GIP', 'ru'),
(1089, 'Greece', 'Евро', 'EUR', 'ru'),
(1090, 'Greenland (Denmark)', 'Датская крона', 'DKK', 'ru'),
(1091, 'Grenada', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1092, 'Guadeloupe (France)', 'Евро', 'EUR', 'ru'),
(1093, 'Guam (USA)', 'Доллар США', 'USD', 'ru'),
(1094, 'Guatemala', 'Гватемальский кетсаль', 'GTQ', 'ru'),
(1095, 'Guernsey (UK)', 'Guernsey Pound', 'GGP', 'ru'),
(1096, 'Guinea', 'Гвинейский франк', 'GNF', 'ru'),
(1097, 'Guinea-Bissau', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1098, 'Guyana', 'Гайанский доллар', 'GYD', 'ru'),
(1099, 'Haiti', 'Гаитянский гурд', 'HTG', 'ru'),
(1100, 'Honduras', 'Гондурасская лемпира', 'HNL', 'ru'),
(1101, 'Hong Kong (China)', 'Гонконгский доллар', 'HKD', 'ru'),
(1102, 'Hungary', 'Венгерский форинт', 'HUF', 'ru'),
(1103, 'Iceland', 'Исландская крона', 'ISK', 'ru'),
(1104, 'India', 'Индийская рупия', 'INR', 'ru'),
(1105, 'Indonesia', 'Индонезийская рупия', 'IDR', 'ru'),
(1106, 'International Monetary Fund (1IMF)', 'SDR (1Special Drawing Right)', 'XDR', 'ru'),
(1107, 'Iran', 'Иранский риал', 'IRR', 'ru'),
(1108, 'Iraq', 'Иракский динар', 'IQD', 'ru'),
(1109, 'Ireland', 'Евро', 'EUR', 'ru'),
(1110, 'Isle of Man (UK)', 'Manx pound', 'IMP', 'ru'),
(1111, 'Israel', 'Новый израильский шекель', 'ILS', 'ru'),
(1112, 'Italy', 'Евро', 'EUR', 'ru'),
(1113, 'Jamaica', 'Ямайский доллар', 'JMD', 'ru'),
(1114, 'Japan', 'Японская иена', 'JPY', 'ru'),
(1115, 'Jersey (UK)', 'Jersey pound', 'JEP', 'ru'),
(1116, 'Jordan', 'Иорданский динар', 'JOD', 'ru'),
(1117, 'Kazakhstan', 'Казахский тенге', 'KZT', 'ru'),
(1118, 'Kenya', 'Кенийский шиллинг', 'KES', 'ru'),
(1119, 'Kiribati', 'Австралийский доллар', 'AUD', 'ru'),
(1120, 'Kosovo', 'Евро', 'EUR', 'ru'),
(1121, 'Kuwait', 'Кувейтский динар', 'KWD', 'ru'),
(1122, 'Kyrgyzstan', 'Киргизский сом', 'KGS', 'ru'),
(1123, 'Laos', 'Лаосский кип', 'LAK', 'ru'),
(1124, 'Latvia', 'Евро', 'EUR', 'ru'),
(1125, 'Lebanon', 'Ливанский фунт', 'LBP', 'ru'),
(1126, 'Lesotho', 'Лоти', 'LSL', 'ru'),
(1127, 'Liberia', 'Либерийский доллар', 'LRD', 'ru'),
(1128, 'Libya', 'Ливийский динар', 'LYD', 'ru'),
(1129, 'Liechtenstein', 'Швейцарский франк', 'CHF', 'ru'),
(1130, 'Lithuania', 'Евро', 'EUR', 'ru'),
(1131, 'Luxembourg', 'Евро', 'EUR', 'ru'),
(1132, 'Macau (China)', 'Патака Макао', 'MOP', 'ru'),
(1133, 'Madagascar', 'Малагасийский ариари', 'MGA', 'ru'),
(1134, 'Malawi', 'Малавийская квача', 'MWK', 'ru'),
(1135, 'Malaysia', 'Малайзийский ринггит', 'MYR', 'ru'),
(1136, 'Maldives', 'Мальдивская руфия', 'MVR', 'ru'),
(1137, 'Mali', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1138, 'Malta', 'Евро', 'EUR', 'ru'),
(1139, 'Marshall Islands', 'Доллар США', 'USD', 'ru'),
(1140, 'Martinique (France)', 'Евро', 'EUR', 'ru'),
(1141, 'Mauritania', 'Mauritanian ouguiya', 'MRU', 'ru'),
(1142, 'Mauritius', 'Маврикийская рупия', 'MUR', 'ru'),
(1143, 'Mayotte (France)', 'Евро', 'EUR', 'ru'),
(1144, 'Mexico', 'Мексиканское песо', 'MXN', 'ru'),
(1145, 'Micronesia', 'Доллар США', 'USD', 'ru'),
(1146, 'Moldova', 'Молдавский лей', 'MDL', 'ru'),
(1147, 'Monaco', 'Евро', 'EUR', 'ru'),
(1148, 'Mongolia', 'Монгольский тугрик', 'MNT', 'ru'),
(1149, 'Montenegro', 'Евро', 'EUR', 'ru'),
(1150, 'Montserrat (UK)', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1151, 'Morocco', 'Марокканский дирхам', 'MAD', 'ru'),
(1152, 'Mozambique', 'Мозамбикский метикал', 'MZN', 'ru'),
(1153, 'Myanmar (formerly Burma)', 'Мьянманский кьят', 'MMK', 'ru'),
(1154, 'Namibia', 'Доллар Намибии', 'NAD', 'ru'),
(1155, 'Nauru', 'Австралийский доллар', 'AUD', 'ru'),
(1156, 'Nepal', 'Непальская рупия', 'NPR', 'ru'),
(1157, 'Netherlands', 'Евро', 'EUR', 'ru'),
(1158, 'New Caledonia (France)', 'Французский тихоокеанский франк', 'XPF', 'ru'),
(1159, 'New Zealand', 'Новозеландский доллар', 'NZD', 'ru'),
(1160, 'Nicaragua', 'Никарагуанская кордоба', 'NIO', 'ru'),
(1161, 'Niger', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1162, 'Nigeria', 'Нигерийская найра', 'NGN', 'ru'),
(1163, 'Niue (New Zealand)', 'Новозеландский доллар', 'NZD', 'ru'),
(1164, 'Norfolk Island (Australia)', 'Австралийский доллар', 'AUD', 'ru'),
(1165, 'Northern Mariana Islands (USA)', 'Доллар США', 'USD', 'ru'),
(1166, 'North Korea', 'Северокорейская вона', 'KPW', 'ru'),
(1167, 'North Macedonia (formerly Macedonia)', 'Македонский денар', 'MKD', 'ru'),
(1168, 'Norway', 'Норвежская крона', 'NOK', 'ru'),
(1169, 'Oman', 'Оманский риал', 'OMR', 'ru'),
(1170, 'Pakistan', 'Пакистанская рупия', 'PKR', 'ru'),
(1171, 'Palau', 'Доллар США', 'USD', 'ru'),
(1172, 'Palestine', 'Новый израильский шекель', 'ILS', 'ru'),
(1173, 'Panama', 'Доллар США', 'USD', 'ru'),
(1174, 'Papua New Guinea', 'Кина Папуа – Новой Гвинеи', 'PGK', 'ru'),
(1175, 'Paraguay', 'Парагвайский гуарани', 'PYG', 'ru'),
(1176, 'Peru', 'Перуанский соль', 'PEN', 'ru'),
(1177, 'Philippines', 'Филиппинское песо', 'PHP', 'ru'),
(1178, 'Pitcairn Islands (UK)', 'Новозеландский доллар', 'NZD', 'ru'),
(1179, 'Poland', 'Польский злотый', 'PLN', 'ru'),
(1180, 'Portugal', 'Евро', 'EUR', 'ru'),
(1181, 'Puerto Rico (USA)', 'Доллар США', 'USD', 'ru'),
(1182, 'Qatar', 'Катарский риал', 'QAR', 'ru'),
(1183, 'Reunion (France)', 'Евро', 'EUR', 'ru'),
(1184, 'Romania', 'Румынский лей', 'RON', 'ru'),
(1185, 'Russia', 'Российский рубль', 'RUB', 'ru'),
(1186, 'Rwanda', 'Франк Руанды', 'RWF', 'ru'),
(1187, 'Saba (Netherlands)', 'Доллар США', 'USD', 'ru'),
(1188, 'Saint Barthelemy (France)', 'Евро', 'EUR', 'ru'),
(1189, 'Saint Helena (UK)', 'Фунт острова Святой Елены', 'SHP', 'ru'),
(1190, 'Saint Kitts and Nevis', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1191, 'Saint Lucia', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1192, 'Saint Martin (France)', 'Евро', 'EUR', 'ru'),
(1193, 'Saint Pierre and Miquelon (France)', 'Евро', 'EUR', 'ru'),
(1194, 'Saint Vincent and the Grenadines', 'Восточно-карибский доллар', 'XCD', 'ru'),
(1195, 'Samoa', 'Самоанская тала', 'WST', 'ru'),
(1196, 'San Marino', 'Евро', 'EUR', 'ru'),
(1197, 'Sao Tome and Principe', 'Sao Tome and Principe dobra', 'STN', 'ru'),
(1198, 'Saudi Arabia', 'Саудовский риял', 'SAR', 'ru'),
(1199, 'Senegal', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1200, 'Serbia', 'Сербский динар', 'RSD', 'ru'),
(1201, 'Seychelles', 'Сейшельская рупия', 'SCR', 'ru'),
(1202, 'Sierra Leone', 'Леоне', 'SLL', 'ru'),
(1203, 'Singapore', 'Сингапурский доллар', 'SGD', 'ru'),
(1204, 'Sint Eustatius (Netherlands)', 'Доллар США', 'USD', 'ru'),
(1205, 'Sint Maarten (Netherlands)', 'Нидерландский антильский гульден', 'ANG', 'ru'),
(1206, 'Slovakia', 'Евро', 'EUR', 'ru'),
(1207, 'Slovenia', 'Евро', 'EUR', 'ru'),
(1208, 'Solomon Islands', 'Доллар Соломоновых островов', 'SBD', 'ru'),
(1209, 'Somalia', 'Сомалийский шиллинг', 'SOS', 'ru'),
(1210, 'South Africa', 'Южноафриканский рэнд', 'ZAR', 'ru'),
(1211, 'South Georgia Island (UK)', 'Британский фунт стерлингов', 'GBP', 'ru'),
(1212, 'South Korea', 'Южнокорейская вона', 'KRW', 'ru'),
(1213, 'South Sudan', 'Южносуданский фунт', 'SSP', 'ru'),
(1214, 'Spain', 'Евро', 'EUR', 'ru'),
(1215, 'Sri Lanka', 'Шри-ланкийская рупия', 'LKR', 'ru'),
(1216, 'Sudan', 'Суданский фунт', 'SDG', 'ru'),
(1217, 'Suriname', 'Суринамский доллар', 'SRD', 'ru'),
(1218, 'Svalbard and Jan Mayen (Norway)', 'Норвежская крона', 'NOK', 'ru'),
(1219, 'Sweden', 'Шведская крона', 'SEK', 'ru'),
(1220, 'Switzerland', 'Швейцарский франк', 'CHF', 'ru'),
(1221, 'Syria', 'Сирийский фунт', 'SYP', 'ru'),
(1222, 'Taiwan', 'Новый тайваньский доллар', 'TWD', 'ru'),
(1223, 'Tajikistan', 'Таджикский сомони', 'TJS', 'ru'),
(1224, 'Tanzania', 'Танзанийский шиллинг', 'TZS', 'ru'),
(1225, 'Thailand', 'Таиландский бат', 'THB', 'ru'),
(1226, 'Timor-Leste', 'Доллар США', 'USD', 'ru'),
(1227, 'Togo', 'Франк КФА ВСЕАО', 'XOF', 'ru'),
(1228, 'Tokelau (New Zealand)', 'Новозеландский доллар', 'NZD', 'ru'),
(1229, 'Tonga', 'Тонганская паанга', 'TOP', 'ru'),
(1230, 'Trinidad and Tobago', 'Доллар Тринидада и Тобаго', 'TTD', 'ru'),
(1231, 'Tristan da Cunha (UK)', 'Британский фунт стерлингов', 'GBP', 'ru'),
(1232, 'Tunisia', 'Тунисский динар', 'TND', 'ru'),
(1233, 'Turkey', 'Турецкая лира', 'TRY', 'ru'),
(1234, 'Turkmenistan', 'Новый туркменский манат', 'TMT', 'ru'),
(1235, 'Turks and Caicos Islands (UK)', 'Доллар США', 'USD', 'ru'),
(1236, 'Tuvalu', 'Австралийский доллар', 'AUD', 'ru'),
(1237, 'Uganda', 'Угандийский шиллинг', 'UGX', 'ru'),
(1238, 'Ukraine', 'Украинская гривна', 'UAH', 'ru'),
(1239, 'United Arab Emirates', 'Дирхам ОАЭ', 'AED', 'ru'),
(1240, 'United Kingdom', 'Британский фунт стерлингов', 'GBP', 'ru'),
(1241, 'United States of America', 'Доллар США', 'USD', 'ru'),
(1242, 'Uruguay', 'Уругвайское песо', 'UYU', 'ru'),
(1243, 'US Virgin Islands (USA)', 'Доллар США', 'USD', 'ru'),
(1244, 'Uzbekistan', 'Узбекский сум', 'UZS', 'ru'),
(1245, 'Vanuatu', 'Вату Вануату', 'VUV', 'ru'),
(1246, 'Vatican City (1Holy See)', 'Евро', 'EUR', 'ru'),
(1247, 'Venezuela', 'Venezuelan bolivar', 'VES', 'ru'),
(1248, 'Vietnam', 'Вьетнамский донг', 'VND', 'ru'),
(1249, 'Wake Island (USA)', 'Доллар США', 'USD', 'ru'),
(1250, 'Wallis and Futuna (France)', 'Французский тихоокеанский франк', 'XPF', 'ru'),
(1251, 'Yemen', 'Йеменский риал', 'YER', 'ru'),
(1252, 'Zambia', 'Замбийская квача', 'ZMW', 'ru'),
(1253, 'Zimbabwe', 'Доллар США', 'USD', 'ru'),
(1254, '', 'Золото', 'XAU', 'ru'),
(1255, '', 'Серебро', 'XAG', 'ru'),
(1256, '', 'Платина', 'XPT', 'ru'),
(1257, '', 'Палладий', 'XPD', 'ru'),
(2001, 'Afghanistan', 'Афганський афгані', 'AFN', 'uk'),
(2002, 'Akrotiri and Dhekelia (UK)', 'Євро', 'EUR', 'uk'),
(2003, 'Aland Islands (Finland)', 'Євро', 'EUR', 'uk'),
(2004, 'Albania', 'Албанський лек', 'ALL', 'uk'),
(2005, 'Algeria', 'Алжирський динар', 'DZD', 'uk'),
(2006, 'American Samoa (USA)', 'Долар США', 'USD', 'uk'),
(2007, 'Andorra', 'Євро', 'EUR', 'uk'),
(2008, 'Angola', 'Ангольська кванза', 'AOA', 'uk'),
(2009, 'Anguilla (UK)', 'Східнокарибський долар', 'XCD', 'uk'),
(2010, 'Antigua and Barbuda', 'Східнокарибський долар', 'XCD', 'uk'),
(2011, 'Argentina', 'Аргентинський песо', 'ARS', 'uk'),
(2012, 'Armenia', 'Вірменський драм', 'AMD', 'uk'),
(2013, 'Aruba (Netherlands)', 'Арубський флорин', 'AWG', 'uk'),
(2014, 'Ascension Island (UK)', 'Фунт острова Святої Єлени', 'SHP', 'uk'),
(2015, 'Australia', 'Австралійський долар', 'AUD', 'uk'),
(2016, 'Austria', 'Євро', 'EUR', 'uk'),
(2017, 'Azerbaijan', 'Азербайджанський манат', 'AZN', 'uk'),
(2018, 'Bahamas', 'Багамський долар', 'BSD', 'uk'),
(2019, 'Bahrain', 'Бахрейнський динар', 'BHD', 'uk'),
(2020, 'Bangladesh', 'Бангладеська така', 'BDT', 'uk'),
(2021, 'Barbados', 'Барбадоський долар', 'BBD', 'uk'),
(2022, 'Belarus', 'Білоруський рубль', 'BYN', 'uk'),
(2023, 'Belgium', 'Євро', 'EUR', 'uk'),
(2024, 'Belize', 'Белізький долар', 'BZD', 'uk'),
(2025, 'Benin', 'Західноафриканський франк', 'XOF', 'uk'),
(2026, 'Bermuda (UK)', 'Бермудський долар', 'BMD', 'uk'),
(2027, 'Bhutan', 'Бутанський нгултрум', 'BTN', 'uk'),
(2028, 'Bolivia', 'Болівійський болівіано', 'BOB', 'uk'),
(2029, 'Bonaire (Netherlands)', 'Долар США', 'USD', 'uk'),
(2030, 'Bosnia and Herzegovina', 'Конвертована марка Боснії і Герцеговини', 'BAM', 'uk'),
(2031, 'Botswana', 'Ботсванська пула', 'BWP', 'uk'),
(2032, 'Brazil', 'Бразильський реал', 'BRL', 'uk'),
(2033, 'British Indian Ocean Territory (UK)', 'Долар США', 'USD', 'uk'),
(2034, 'British Virgin Islands (UK)', 'Долар США', 'USD', 'uk'),
(2035, 'Brunei', 'Брунейський долар', 'BND', 'uk'),
(2036, 'Bulgaria', 'Болгарський лев', 'BGN', 'uk'),
(2037, 'Burkina Faso', 'Західноафриканський франк', 'XOF', 'uk'),
(2038, 'Burundi', 'Бурундійський франк', 'BIF', 'uk'),
(2039, 'Cabo Verde', 'Ескудо Кабо-Верде', 'CVE', 'uk'),
(2040, 'Cambodia', 'Камбоджійський рієль', 'KHR', 'uk'),
(2041, 'Cameroon', 'Центральноафриканський франк', 'XAF', 'uk'),
(2042, 'Canada', 'Канадський долар', 'CAD', 'uk'),
(2043, 'Caribbean Netherlands (Netherlands)', 'Долар США', 'USD', 'uk'),
(2044, 'Cayman Islands (UK)', 'Долар Кайманових островів', 'KYD', 'uk'),
(2045, 'Central African Republic', 'Центральноафриканський франк', 'XAF', 'uk'),
(2046, 'Chad', 'Центральноафриканський франк', 'XAF', 'uk'),
(2047, 'Chatham Islands (New Zealand)', 'Новозеландський долар', 'NZD', 'uk'),
(2048, 'Chile', 'Чилійський песо', 'CLP', 'uk'),
(2049, 'China', 'Китайський юань', 'CNY', 'uk'),
(2050, 'Christmas Island (Australia)', 'Австралійський долар', 'AUD', 'uk'),
(2051, 'Cocos (10Keeling) Islands (Australia)', 'Австралійський долар', 'AUD', 'uk'),
(2052, 'Colombia', 'Колумбійський песо', 'COP', 'uk'),
(2053, 'Comoros', 'Коморський франк', 'KMF', 'uk'),
(2054, 'Congo, Democratic Republic of the', 'Конголезький франк', 'CDF', 'uk'),
(2055, 'Congo, Republic of the', 'Центральноафриканський франк', 'XAF', 'uk'),
(2056, 'Cook Islands (New Zealand)', 'Cook Islands dollar', '---', 'uk'),
(2057, 'Costa Rica', 'Костариканський колон', 'CRC', 'uk'),
(2058, 'Cote d\'Ivoire', 'Західноафриканський франк', 'XOF', 'uk'),
(2059, 'Croatia', 'Хорватська куна', 'HRK', 'uk'),
(2060, 'Cuba', 'Кубинський песо', 'CUP', 'uk'),
(2061, 'Curacao (Netherlands)', 'Нідерландський антильський гульден', 'ANG', 'uk'),
(2062, 'Cyprus', 'Євро', 'EUR', 'uk'),
(2063, 'Czechia', 'Чеська крона', 'CZK', 'uk'),
(2064, 'Denmark', 'Данська крона', 'DKK', 'uk'),
(2065, 'Djibouti', 'Джибутійський франк', 'DJF', 'uk'),
(2066, 'Dominica', 'Східнокарибський долар', 'XCD', 'uk'),
(2067, 'Dominican Republic', 'Домініканський песо', 'DOP', 'uk'),
(2068, 'Ecuador', 'Долар США', 'USD', 'uk'),
(2069, 'Egypt', 'Єгипетський фунт', 'EGP', 'uk'),
(2070, 'El Salvador', 'Долар США', 'USD', 'uk'),
(2071, 'Equatorial Guinea', 'Центральноафриканський франк', 'XAF', 'uk'),
(2072, 'Eritrea', 'Еритрейська накфа', 'ERN', 'uk'),
(2073, 'Estonia', 'Євро', 'EUR', 'uk'),
(2074, 'Eswatini (formerly Swaziland)', 'Свазілендський лілангені', 'SZL', 'uk'),
(2075, 'Ethiopia', 'Ефіопський бир', 'ETB', 'uk'),
(2076, 'Falkland Islands (UK)', 'Фунт Фолклендських островів', 'FKP', 'uk'),
(2077, 'Faroe Islands (Denmark)', 'Faroese krona', '---', 'uk'),
(2078, 'Fiji', 'Фіджійський долар', 'FJD', 'uk'),
(2079, 'Finland', 'Євро', 'EUR', 'uk'),
(2080, 'France', 'Євро', 'EUR', 'uk'),
(2081, 'French Guiana (France)', 'Євро', 'EUR', 'uk'),
(2082, 'French Polynesia (France)', 'Французький тихоокеанський франк', 'XPF', 'uk'),
(2083, 'Gabon', 'Центральноафриканський франк', 'XAF', 'uk'),
(2084, 'Gambia', 'Гамбійський даласі', 'GMD', 'uk'),
(2085, 'Georgia', 'Грузинський ларі', 'GEL', 'uk'),
(2086, 'Germany', 'Євро', 'EUR', 'uk'),
(2087, 'Ghana', 'Ганський седі', 'GHS', 'uk'),
(2088, 'Gibraltar (UK)', 'Гібралтарський фунт', 'GIP', 'uk'),
(2089, 'Greece', 'Євро', 'EUR', 'uk'),
(2090, 'Greenland (Denmark)', 'Данська крона', 'DKK', 'uk'),
(2091, 'Grenada', 'Східнокарибський долар', 'XCD', 'uk'),
(2092, 'Guadeloupe (France)', 'Євро', 'EUR', 'uk'),
(2093, 'Guam (USA)', 'Долар США', 'USD', 'uk'),
(2094, 'Guatemala', 'Гватемальський кетсаль', 'GTQ', 'uk'),
(2095, 'Guernsey (UK)', 'Guernsey Pound', 'GGP', 'uk'),
(2096, 'Guinea', 'Гвінейський франк', 'GNF', 'uk'),
(2097, 'Guinea-Bissau', 'Західноафриканський франк', 'XOF', 'uk'),
(2098, 'Guyana', 'Гаянський долар', 'GYD', 'uk'),
(2099, 'Haiti', 'Гаїтянський гурд', 'HTG', 'uk'),
(2100, 'Honduras', 'Гондураська лемпіра', 'HNL', 'uk'),
(2101, 'Hong Kong (China)', 'Гонконгський долар', 'HKD', 'uk'),
(2102, 'Hungary', 'Угорський форинт', 'HUF', 'uk'),
(2103, 'Iceland', 'Ісландська крона', 'ISK', 'uk'),
(2104, 'India', 'Індійська рупія', 'INR', 'uk'),
(2105, 'Indonesia', 'Індонезійська рупія', 'IDR', 'uk'),
(2106, 'International Monetary Fund (1IMF)', 'SDR (1Special Drawing Right)', 'XDR', 'uk'),
(2107, 'Iran', 'Іранський ріал', 'IRR', 'uk'),
(2108, 'Iraq', 'Іракський динар', 'IQD', 'uk'),
(2109, 'Ireland', 'Євро', 'EUR', 'uk'),
(2110, 'Isle of Man (UK)', 'Manx pound', 'IMP', 'uk'),
(2111, 'Israel', 'Ізраїльський новий шекель', 'ILS', 'uk'),
(2112, 'Italy', 'Євро', 'EUR', 'uk'),
(2113, 'Jamaica', 'Ямайський долар', 'JMD', 'uk'),
(2114, 'Japan', 'Японська єна', 'JPY', 'uk'),
(2115, 'Jersey (UK)', 'Jersey pound', 'JEP', 'uk'),
(2116, 'Jordan', 'Йорданський динар', 'JOD', 'uk'),
(2117, 'Kazakhstan', 'Казахстанський тенге', 'KZT', 'uk'),
(2118, 'Kenya', 'Кенійський шилінг', 'KES', 'uk'),
(2119, 'Kiribati', 'Австралійський долар', 'AUD', 'uk'),
(2120, 'Kosovo', 'Євро', 'EUR', 'uk'),
(2121, 'Kuwait', 'Кувейтський динар', 'KWD', 'uk'),
(2122, 'Kyrgyzstan', 'Киргизький сом', 'KGS', 'uk'),
(2123, 'Laos', 'Лаоський кіп', 'LAK', 'uk'),
(2124, 'Latvia', 'Євро', 'EUR', 'uk'),
(2125, 'Lebanon', 'Ліванський фунт', 'LBP', 'uk'),
(2126, 'Lesotho', 'Лесотський лоті', 'LSL', 'uk'),
(2127, 'Liberia', 'Ліберійський долар', 'LRD', 'uk'),
(2128, 'Libya', 'Лівійський динар', 'LYD', 'uk'),
(2129, 'Liechtenstein', 'Швейцарський франк', 'CHF', 'uk'),
(2130, 'Lithuania', 'Євро', 'EUR', 'uk'),
(2131, 'Luxembourg', 'Євро', 'EUR', 'uk'),
(2132, 'Macau (China)', 'Патака Макао', 'MOP', 'uk'),
(2133, 'Madagascar', 'Малагасійський аріарі', 'MGA', 'uk'),
(2134, 'Malawi', 'Малавійська квача', 'MWK', 'uk'),
(2135, 'Malaysia', 'Малайзійський рингіт', 'MYR', 'uk'),
(2136, 'Maldives', 'Мальдівська руфія', 'MVR', 'uk'),
(2137, 'Mali', 'Західноафриканський франк', 'XOF', 'uk'),
(2138, 'Malta', 'Євро', 'EUR', 'uk'),
(2139, 'Marshall Islands', 'Долар США', 'USD', 'uk'),
(2140, 'Martinique (France)', 'Євро', 'EUR', 'uk'),
(2141, 'Mauritania', 'Mauritanian ouguiya', 'MRU', 'uk'),
(2142, 'Mauritius', 'Маврикійська рупія', 'MUR', 'uk'),
(2143, 'Mayotte (France)', 'Євро', 'EUR', 'uk'),
(2144, 'Mexico', 'Мексиканський песо', 'MXN', 'uk'),
(2145, 'Micronesia', 'Долар США', 'USD', 'uk'),
(2146, 'Moldova', 'Молдовський лей', 'MDL', 'uk'),
(2147, 'Monaco', 'Євро', 'EUR', 'uk'),
(2148, 'Mongolia', 'Монгольський тугрик', 'MNT', 'uk'),
(2149, 'Montenegro', 'Євро', 'EUR', 'uk'),
(2150, 'Montserrat (UK)', 'Східнокарибський долар', 'XCD', 'uk'),
(2151, 'Morocco', 'Марокканський дирхам', 'MAD', 'uk'),
(2152, 'Mozambique', 'Мозамбіцький метикал', 'MZN', 'uk'),
(2153, 'Myanmar (formerly Burma)', 'Кʼят Мʼянми', 'MMK', 'uk'),
(2154, 'Namibia', 'Намібійський долар', 'NAD', 'uk'),
(2155, 'Nauru', 'Австралійський долар', 'AUD', 'uk'),
(2156, 'Nepal', 'Непальська рупія', 'NPR', 'uk'),
(2157, 'Netherlands', 'Євро', 'EUR', 'uk'),
(2158, 'New Caledonia (France)', 'Французький тихоокеанський франк', 'XPF', 'uk'),
(2159, 'New Zealand', 'Новозеландський долар', 'NZD', 'uk'),
(2160, 'Nicaragua', 'Нікарагуанська кордоба', 'NIO', 'uk'),
(2161, 'Niger', 'Західноафриканський франк', 'XOF', 'uk'),
(2162, 'Nigeria', 'Нігерійська найра', 'NGN', 'uk'),
(2163, 'Niue (New Zealand)', 'Новозеландський долар', 'NZD', 'uk'),
(2164, 'Norfolk Island (Australia)', 'Австралійський долар', 'AUD', 'uk'),
(2165, 'Northern Mariana Islands (USA)', 'Долар США', 'USD', 'uk'),
(2166, 'North Korea', 'Північнокорейський вон', 'KPW', 'uk'),
(2167, 'North Macedonia (formerly Macedonia)', 'Македонський денар', 'MKD', 'uk'),
(2168, 'Norway', 'Норвезька крона', 'NOK', 'uk'),
(2169, 'Oman', 'Оманський ріал', 'OMR', 'uk'),
(2170, 'Pakistan', 'Пакистанська рупія', 'PKR', 'uk'),
(2171, 'Palau', 'Долар США', 'USD', 'uk'),
(2172, 'Palestine', 'Ізраїльський новий шекель', 'ILS', 'uk'),
(2173, 'Panama', 'Долар США', 'USD', 'uk'),
(2174, 'Papua New Guinea', 'Кіна Папуа-Нової Ґвінеї', 'PGK', 'uk'),
(2175, 'Paraguay', 'Парагвайський гуарані', 'PYG', 'uk'),
(2176, 'Peru', 'Перуанський новий сол', 'PEN', 'uk'),
(2177, 'Philippines', 'Філіппінський песо', 'PHP', 'uk'),
(2178, 'Pitcairn Islands (UK)', 'Новозеландський долар', 'NZD', 'uk'),
(2179, 'Poland', 'Польський злотий', 'PLN', 'uk'),
(2180, 'Portugal', 'Євро', 'EUR', 'uk'),
(2181, 'Puerto Rico (USA)', 'Долар США', 'USD', 'uk'),
(2182, 'Qatar', 'Катарський ріал', 'QAR', 'uk'),
(2183, 'Reunion (France)', 'Євро', 'EUR', 'uk'),
(2184, 'Romania', 'Румунський лей', 'RON', 'uk'),
(2185, 'Russia', 'Російський рубль', 'RUB', 'uk'),
(2186, 'Rwanda', 'Руандійський франк', 'RWF', 'uk'),
(2187, 'Saba (Netherlands)', 'Долар США', 'USD', 'uk'),
(2188, 'Saint Barthelemy (France)', 'Євро', 'EUR', 'uk'),
(2189, 'Saint Helena (UK)', 'Фунт острова Святої Єлени', 'SHP', 'uk'),
(2190, 'Saint Kitts and Nevis', 'Східнокарибський долар', 'XCD', 'uk'),
(2191, 'Saint Lucia', 'Східнокарибський долар', 'XCD', 'uk'),
(2192, 'Saint Martin (France)', 'Євро', 'EUR', 'uk'),
(2193, 'Saint Pierre and Miquelon (France)', 'Євро', 'EUR', 'uk'),
(2194, 'Saint Vincent and the Grenadines', 'Східнокарибський долар', 'XCD', 'uk'),
(2195, 'Samoa', 'Самоанська тала', 'WST', 'uk'),
(2196, 'San Marino', 'Євро', 'EUR', 'uk'),
(2197, 'Sao Tome and Principe', 'Sao Tome and Principe dobra', 'STN', 'uk'),
(2198, 'Saudi Arabia', 'Саудівський ріал', 'SAR', 'uk'),
(2199, 'Senegal', 'Західноафриканський франк', 'XOF', 'uk'),
(2200, 'Serbia', 'Сербський динар', 'RSD', 'uk'),
(2201, 'Seychelles', 'Сейшельська рупія', 'SCR', 'uk'),
(2202, 'Sierra Leone', 'Леоне Сьєрра-Леоне', 'SLL', 'uk'),
(2203, 'Singapore', 'Сінгапурський долар', 'SGD', 'uk'),
(2204, 'Sint Eustatius (Netherlands)', 'Долар США', 'USD', 'uk'),
(2205, 'Sint Maarten (Netherlands)', 'Нідерландський антильський гульден', 'ANG', 'uk'),
(2206, 'Slovakia', 'Євро', 'EUR', 'uk'),
(2207, 'Slovenia', 'Євро', 'EUR', 'uk'),
(2208, 'Solomon Islands', 'Долар Соломонових Островів', 'SBD', 'uk'),
(2209, 'Somalia', 'Сомалійський шилінг', 'SOS', 'uk'),
(2210, 'South Africa', 'Південноафриканський ранд', 'ZAR', 'uk'),
(2211, 'South Georgia Island (UK)', 'Англійський фунт', 'GBP', 'uk'),
(2212, 'South Korea', 'Південнокорейський вон', 'KRW', 'uk'),
(2213, 'South Sudan', 'Південносуданський фунт', 'SSP', 'uk'),
(2214, 'Spain', 'Євро', 'EUR', 'uk'),
(2215, 'Sri Lanka', 'Шрі-ланкійська рупія', 'LKR', 'uk'),
(2216, 'Sudan', 'Суданський фунт', 'SDG', 'uk'),
(2217, 'Suriname', 'Суринамський долар', 'SRD', 'uk'),
(2218, 'Svalbard and Jan Mayen (Norway)', 'Норвезька крона', 'NOK', 'uk'),
(2219, 'Sweden', 'Шведська крона', 'SEK', 'uk'),
(2220, 'Switzerland', 'Швейцарський франк', 'CHF', 'uk'),
(2221, 'Syria', 'Сирійський фунт', 'SYP', 'uk'),
(2222, 'Taiwan', 'Новий тайванський долар', 'TWD', 'uk'),
(2223, 'Tajikistan', 'Таджицький сомоні', 'TJS', 'uk'),
(2224, 'Tanzania', 'Танзанійський шилінг', 'TZS', 'uk'),
(2225, 'Thailand', 'Таїландський бат', 'THB', 'uk'),
(2226, 'Timor-Leste', 'Долар США', 'USD', 'uk'),
(2227, 'Togo', 'Західноафриканський франк', 'XOF', 'uk'),
(2228, 'Tokelau (New Zealand)', 'Новозеландський долар', 'NZD', 'uk'),
(2229, 'Tonga', 'Тонґанська паанга', 'TOP', 'uk'),
(2230, 'Trinidad and Tobago', 'Долар Трінідаду і Тобаґо', 'TTD', 'uk'),
(2231, 'Tristan da Cunha (UK)', 'Англійський фунт', 'GBP', 'uk'),
(2232, 'Tunisia', 'Туніський динар', 'TND', 'uk'),
(2233, 'Turkey', 'Турецька ліра', 'TRY', 'uk'),
(2234, 'Turkmenistan', 'Туркменський манат', 'TMT', 'uk'),
(2235, 'Turks and Caicos Islands (UK)', 'Долар США', 'USD', 'uk'),
(2236, 'Tuvalu', 'Австралійський долар', 'AUD', 'uk'),
(2237, 'Uganda', 'Угандійський шилінг', 'UGX', 'uk'),
(2238, 'Ukraine', 'Українська гривня', 'UAH', 'uk'),
(2239, 'United Arab Emirates', 'Дирхам ОАЕ', 'AED', 'uk'),
(2240, 'United Kingdom', 'Англійський фунт', 'GBP', 'uk'),
(2241, 'United States of America', 'Долар США', 'USD', 'uk'),
(2242, 'Uruguay', 'Уругвайський песо', 'UYU', 'uk'),
(2243, 'US Virgin Islands (USA)', 'Долар США', 'USD', 'uk'),
(2244, 'Uzbekistan', 'Узбецький сум', 'UZS', 'uk'),
(2245, 'Vanuatu', 'Вануатський вату', 'VUV', 'uk'),
(2246, 'Vatican City (1Holy See)', 'Євро', 'EUR', 'uk'),
(2247, 'Venezuela', 'Venezuelan bolivar', 'VES', 'uk'),
(2248, 'Vietnam', 'Вʼєтнамський донг', 'VND', 'uk'),
(2249, 'Wake Island (USA)', 'Долар США', 'USD', 'uk'),
(2250, 'Wallis and Futuna (France)', 'Французький тихоокеанський франк', 'XPF', 'uk'),
(2251, 'Yemen', 'Єменський ріал', 'YER', 'uk'),
(2252, 'Zambia', 'Замбійська квача', 'ZMW', 'uk'),
(2253, 'Zimbabwe', 'Долар США', 'USD', 'uk'),
(2254, '', 'Золото', 'XAU', 'uk'),
(2255, '', 'Срібло', 'XAG', 'uk'),
(2256, '', 'Платіна', 'XPT', 'uk'),
(2257, '', 'Паладій', 'XPD', 'uk');
